// Project and PR submissions for the "Back to the Metadata" hackathon.
// Sourced from the hackathon submission form (projects.csv).

const winningProjects = [
	{
		teamName: "Himanshu",
		projectTitle: "OpenMetadata Hackathon Winner",
		description:
			"Winning project for the Back to the Metadata hackathon, built on OpenMetadata.",
		githubLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/H3tvkptnSZ4",
		prize: "MacBook Neo",
	},
	{
		teamName: "Prasanth Cherukuri",
		projectTitle: "OpenMetadata Hackathon Winner",
		description:
			"Winning project for the Back to the Metadata hackathon, built on OpenMetadata.",
		githubLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/B3b07ktNcCs",
		prize: "iPad Tablet",
	},
	{
		teamName: "DUNE",
		projectTitle: "OpenMetadata Hackathon Winner",
		description:
			"Winning project for the Back to the Metadata hackathon, built on OpenMetadata.",
		githubLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/0R7zc1VNJdE",
		prize: "Keychron Keyboard",
	},
];

type SubmittedProject = {
	team: string;
	submitter: string;
	isSolo: boolean;
	title: string;
	github: string;
	deployed: string;
	youtube: string;
};

const submittedProjects: SubmittedProject[] = [
	{
		team: "A Jaswanth",
		submitter: "A Jaswanth",
		isSolo: true,
		title: "India's DPDP Act 2023 came into effect with penalties up to ₹250 crore per vi...",
		github: "https://github.com/Alkur123/Agies-AI-Real-time-PII-Governance-Compliance-Engine-for-OpenMetadata",
		deployed: "https://dnrvkokqdpg2n.cloudfront.net",
		youtube: "https://youtu.be/zqr92NtPA2k",
	},
	{
		team: "Aakash Jaiswal",
		submitter: "Aakash Jaiswal",
		isSolo: true,
		title: "Metagent",
		github: "https://github.com/jaiswalraj03014/metagent",
		deployed: "https://metagent.vercel.app",
		youtube: "https://youtu.be/lLQNTpjrGrk",
	},
	{
		team: "Aaryan Guglani",
		submitter: "Aaryan Guglani",
		isSolo: true,
		title: "CHRONOS",
		github: "https://github.com/guglxni/chronos",
		deployed: "https://chronos-frontend-eight.vercel.app",
		youtube: "https://youtu.be/-hHM1eSMRY0",
	},
	{
		team: "Abhay Singh",
		submitter: "Abhay Singh",
		isSolo: true,
		title: "Sentinel",
		github: "https://github.com/abhay-codes07/OpenMeta",
		deployed: "",
		youtube: "https://youtu.be/Eb0EQVwpUKc?si=JFb84ebIHNrE54e8",
	},
	{
		team: "Abhirav Joshi",
		submitter: "Abhirav Joshi",
		isSolo: true,
		title: "MetaSift",
		github: "https://github.com/blueberrylinux/metasift",
		deployed: "https://sandbox.metasift.org/",
		youtube: "https://youtu.be/BmMrq-hxnHM",
	},
	{
		team: "Abhishek Pati",
		submitter: "Abhishek Pati",
		isSolo: true,
		title: "TimeTravel",
		github: "https://github.com/patiabhishek123/TimeTravel",
		deployed: "",
		youtube: "https://youtu.be/wk2kMBIqZTM",
	},
	{
		team: "Adarsh Jha",
		submitter: "Adarsh Jha",
		isSolo: true,
		title: "MetaGuard AI",
		github: "https://github.com/adarsh-jha-dev/metaguard-ai",
		deployed: "https://metaguard-ai.vercel.app/",
		youtube: "https://youtu.be/M1WNJdI5WSQ",
	},
	{
		team: "Adejoke",
		submitter: "Adejoke",
		isSolo: true,
		title: "MetaFlux",
		github: "https://github.com/natureloved/MetaFlux",
		deployed: "https://metaflux-six.vercel.app/",
		youtube: "https://youtu.be/WSV2rrW2MeY",
	},
	{
		team: "Aditya Kumar Puri",
		submitter: "Aditya Kumar Puri",
		isSolo: true,
		title: "Brings Kestra into OpenMetadata as a first-class pipeline source, and adds th...",
		github: "",
		deployed: "",
		youtube: "https://drive.google.com/drive/u/0/folders/1IDvkn7V20GtejqYKTUStojd2uZCXcdqi",
	},
	{
		team: "Adwait Keshari",
		submitter: "Adwait Keshari",
		isSolo: true,
		title: "Every data team dies the same three deaths",
		github: "https://github.com/Adwaitbytes/outatime",
		deployed: "https://outatime-amber.vercel.app/",
		youtube: "https://youtu.be/4gS48RkllVY",
	},
	{
		team: "Agent McFly",
		submitter: "Leandro Eloi Alcatrão",
		isSolo: false,
		title: "OpenMetaMind: Autonomous multi-agent swarm for OpenMetadata data governance",
		github: "https://github.com/leandroea/openmetamind",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=gXNtQEA8mG4",
	},
	{
		team: "Aidhunik India",
		submitter: "Khem Chand",
		isSolo: false,
		title: "SwaggerLens: AI-Powered API Discovery & Governance Pipeline Modern engineerin...",
		github: "https://github.com/IM-GPT/SwaggerLens",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=zOCOXr62HtI",
	},
	{
		team: "Akshat Saxena",
		submitter: "Akshat Saxena",
		isSolo: true,
		title: "MetaGuard",
		github: "https://github.com/AKSHEXXXX/Metaguard",
		deployed: "https://github.com/AKSHEXXXX/Metaguard/pull/6",
		youtube: "https://www.loom.com/share/9420193d7307460daa307edbba4395de",
	},
	{
		team: "Akshit Patel",
		submitter: "Akshit Patel",
		isSolo: true,
		title: "DataChat",
		github: "https://github.com/Akshitpatel25/datachat",
		deployed: "",
		youtube: "https://youtu.be/G-FFrIZod1c?si=EEytNS45RnvZ9q6v",
	},
	{
		team: "algsoch",
		submitter: "vicky kumar",
		isSolo: false,
		title: "Synapse-Graph",
		github: "https://github.com/FiscalMindset/Synapse-Graph",
		deployed: "",
		youtube: "https://youtu.be/idOJYh6TUC8",
	},
	{
		team: "Allen Saji",
		submitter: "Allen Saji",
		isSolo: true,
		title: "Command-line tool for OpenMetadata",
		github: "https://github.com/Allen-Saji/openmetadata-cli",
		deployed: "https://crates.io/crates/omd-cli",
		youtube: "https://youtu.be/TOvpOYci1mU",
	},
	{
		team: "Alpha Labs",
		submitter: "Prantik Pratim Medhi",
		isSolo: false,
		title: "MetaReview",
		github: "https://github.com/prantikmedhi/MetaReview",
		deployed: "",
		youtube: "https://youtu.be/yNNwP9EUDgQ",
	},
	{
		team: "AlphaGo",
		submitter: "Rohan Jain",
		isSolo: false,
		title: "AI-Powered Compliance & Breach Impact Agent for OpenMetadata",
		github: "https://github.com/rohanjain1648/METADATA_HACKATHON",
		deployed: "",
		youtube: "https://drive.google.com/drive/folders/1tcIM25XXkOmUU9R5SQN6mgMOt32GMoJ2?usp=sharing",
	},
	{
		team: "Animesh",
		submitter: "Animesh",
		isSolo: true,
		title: "DataTrust Engine",
		github: "https://github.com/Animesh-86/DataTrust-Engine.git",
		deployed: "https://datatrust-engine.onrender.com/",
		youtube: "https://www.youtube.com/watch?v=nCixYmnYAqg",
	},
	{
		team: "Anish Maheshwari",
		submitter: "Anish Maheshwari",
		isSolo: true,
		title: "Reddit Metadata Intelligence Engine turns messy Reddit data into clear, struc...",
		github: "https://github.com/anish-maheshwari/Reddit-Metadata",
		deployed: "http://ec2-52-23-183-33.compute-1.amazonaws.com:3000/  Note for judges: Since the application is hosted over HTTP (not HTTPS), your browser may show a security warning. Please click \"Advanced\" → \"Continue to site\" to access the application",
		youtube: "https://www.youtube.com/watch?v=jHZWIk83lt8",
	},
	{
		team: "Artemis",
		submitter: "Aum Patel",
		isSolo: false,
		title: "BlastRadius AI enforces data contracts as code",
		github: "https://github.com/patel-aum/BlastRadius",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=tLP8_BlJYHM",
	},
	{
		team: "Ayush Sharma",
		submitter: "Ayush Sharma",
		isSolo: true,
		title: "kubectl-style CLI for OpenMetadata - explore lineage, manage tags, query data...",
		github: "https://github.com/ayushgitmaster/openmetadata-omctl",
		deployed: "",
		youtube: "https://youtu.be/rv55aB7J6ag",
	},
	{
		team: "Balaji Thukuntala",
		submitter: "Balaji Thukuntala",
		isSolo: true,
		title: "ImpactScope",
		github: "https://github.com/BalajiReddy1/Impact-scope",
		deployed: "",
		youtube: "https://youtu.be/AsYAtzQRUU4",
	},
	{
		team: "BavyaSakthivel",
		submitter: "BavyaSakthivel",
		isSolo: true,
		title: "MetaGuardian",
		github: "https://github.com/BAVYASAKTHIVEL-21/metaguardian",
		deployed: "",
		youtube: "https://youtu.be/1mEQ1q2GFJY",
	},
	{
		team: "Bhunesh bansal",
		submitter: "Bhunesh bansal",
		isSolo: true,
		title: "Datastory",
		github: "https://github.com/bansalbhunesh/Datastory",
		deployed: "https://datastory-xi.vercel.app/",
		youtube: "https://youtube.com/shorts/rjHb-FgJZcc?feature=share",
	},
	{
		team: "Binary Brains",
		submitter: "Yashwanth Sai Chennupalli",
		isSolo: false,
		title: "Project Doppelgänger is an autonomous AI system designed to solve the common ...",
		github: "https://github.com/itsroshanharry/Doppelganger-Openmetadata",
		deployed: "",
		youtube: "https://youtu.be/KnzfcsAewHA?si=82C8R1q-CIROuF0Y",
	},
	{
		team: "ChaiTea",
		submitter: "Ammar Alam Khan",
		isSolo: false,
		title: "OpenMetadata Data Context for VS Code is a VSC extension that surfaces table ...",
		github: "https://github.com/anandv29/vscode-openmetadata",
		deployed: "https://marketplace.visualstudio.com/items?itemName=Cygnus-X.datacontext-openmetadata",
		youtube: "https://www.youtube.com/watch?v=hdi6rYq_TvA",
	},
	{
		team: "Chinmay Anand",
		submitter: "Chinmay Anand",
		isSolo: true,
		title: "RealityChecker",
		github: "https://github.com/Chin-mayyy/RealityChecker",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=d-PnX4IHE3M",
	},
	{
		team: "Chirag Shukla",
		submitter: "Chirag Shukla",
		isSolo: true,
		title: "Built a centralized data catalog and metadata governance platform using OpenM",
		github: "https://github.com/BranchIntl/branch_airflow",
		deployed: "https://openmetadata.branch.co/",
		youtube: "https://www.loom.com/share/a887ac478ecb475cb40ed69c14cfdeb0",
	},
	{
		team: "Chirag Tankan",
		submitter: "Chirag Tankan",
		isSolo: true,
		title: "AI based map which detect potholes upcoming to your way and make you alert fo...",
		github: "https://github.com/ChiragTankan/RoadSence",
		deployed: "https://road-sence.vercel.app/",
		youtube: "https://road-sence.vercel.app/",
	},
	{
		team: "Code Without Load",
		submitter: "Dev Grover",
		isSolo: false,
		title: "FluxGuardian",
		github: "https://github.com/AjaySingh-a/fluxguardian",
		deployed: "https://frontend-eight-theta-35.vercel.app/",
		youtube: "https://youtu.be/HPYZcWkim9w?si=mbjtYReQpy5W2o6d",
	},
	{
		team: "CodedDEVS",
		submitter: "Aliameen Kareem",
		isSolo: false,
		title: "LineageGuard : A Semantic Blast Radius for OpenMetadata",
		github: "https://github.com/coded-devs/lineageguard.git",
		deployed: "",
		youtube: "https://youtu.be/XRKgfbboTH4",
	},
	{
		team: "Ctrl+V & Ctrl+S",
		submitter: "Vishal Singh",
		isSolo: false,
		title: "Slack Bot for OpenMetadata is a Python-based Slack bot that brings metadata o...",
		github: "https://github.com/vishaldev21/slack-bot-open-meta-data",
		deployed: "",
		youtube: "https://youtu.be/ND7FDa32xFU",
	},
	{
		team: "Darshan3690",
		submitter: "Darshan Rajput",
		isSolo: false,
		title: "This submission focuses on improving the reliability of OpenMetadata’s omjob",
		github: "",
		deployed: "",
		youtube: "https://youtu.be/ZAT_mc0XJPo",
	},
	{
		team: "Data Drifters",
		submitter: "Monish K S",
		isSolo: false,
		title: "Problem: Critical business data in Notion is often \"invisible\" to data teams",
		github: "https://github.com/Monish-K-S/notion-om-connector/tree/main",
		deployed: "",
		youtube: "https://youtu.be/xA0oYnOMzcs",
	},
	{
		team: "David",
		submitter: "David",
		isSolo: true,
		title: "MetaPulse",
		github: "https://github.com/Lazy-Code-X01/metapulse.git",
		deployed: "https://metapulse-tau.vercel.app",
		youtube: "https://youtu.be/rrnvNoRuoD8",
	},
	{
		team: "Debabrata pattnayak",
		submitter: "Debabrata pattnayak",
		isSolo: true,
		title: "Root cause engine -(It detects broken pipelines,K8s cost usage, alert system ...",
		github: "https://github.com/debaa98/-Root-Cause-Engine",
		deployed: "https://root-cause-engine.vercel.app/",
		youtube: "https://github.com/debaa98/-Root-Cause-Engine",
	},
	{
		team: "Deployed on Friday",
		submitter: "Piyush Kumar",
		isSolo: false,
		title: "ChronoMeta AI: The Agentic Forensic Debugger for OpenMetadata",
		github: "https://github.com/piyushdotcomm/chronometa-ai",
		deployed: "https://chronometa-ai.vercel.app/",
		youtube: "https://www.youtube.com/watch?v=W5WKxOaFZaA",
	},
	{
		team: "dontcode",
		submitter: "Sajal Chandhoke",
		isSolo: false,
		title: "##This is a a OpenMetadata Dashboard this consolidates operational metrics as",
		github: "https://github.com/shnaiiider/BacktoMetaDataHackathon",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=eh-HFhNaleE",
	},
	{
		team: "Dynamic Duo",
		submitter: "Subhashri Sakthivel",
		isSolo: false,
		title: "BreakSight",
		github: "https://github.com/subhashris/openmetadata-hackathon",
		deployed: "",
		youtube: "https://youtu.be/fdgmwpAwqpk",
	},
	{
		team: "Faisal Mehmood",
		submitter: "Faisal Mehmood",
		isSolo: true,
		title: "AI Impact Analysis Agent",
		github: "https://github.com/Faisal77666/Ai-impact-analysis",
		deployed: "",
		youtube: "https://youtu.be/aUfCREfMvjo?si=5Q2-iZdurz7WB2WL",
	},
	{
		team: "First-Duo",
		submitter: "Arnab Chowdhury",
		isSolo: false,
		title: "MetaBot",
		github: "https://github.com/Arnab-13/metabot-openmetadata",
		deployed: "",
		youtube: "https://youtu.be/5URJD77GjY4?si=2AISFcvHs-eX9a2o",
	},
	{
		team: "Forbidden Phishers",
		submitter: "Sarthak Rawat",
		isSolo: false,
		title: "Data pipeline failures cost data teams countless hours of manual investigation",
		github: "https://github.com/SarthakRawat-1/data-doctor",
		deployed: "https://data-doctor-alpha.vercel.app/",
		youtube: "https://youtu.be/KNUAE1Yt_Fg",
	},
	{
		team: "Fortune Techies",
		submitter: "Lateh Larry-Collins AkA",
		isSolo: false,
		title: "FinGuard Sentinel",
		github: "https://github.com/LarryCollinsAka/lineageguard",
		deployed: "",
		youtube: "https://youtu.be/IfLgvoeY-4o",
	},
	{
		team: "FORTUNE TECHIES",
		submitter: "Adeniyi Adeyemi",
		isSolo: false,
		title: "LineageGuard:  real-time risk intelligence layer for data pipelines, detects ...",
		github: "https://github.com/adeyemiadeniyi-dev/lineageguard/tree/feature/docker-build",
		deployed: "https://lineageguard.tripleadev.com",
		youtube: "https://youtu.be/T6UNpjyU2j8?si=VKQ7v_RB3YGImlFM",
	},
	{
		team: "Game Over",
		submitter: "Vipul Kohli",
		isSolo: false,
		title: "Problem",
		github: "https://github.com/Agarwalpratyaksh/Argus",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=jEumkjBS5to",
	},
	{
		team: "Gangaparameshwari.D",
		submitter: "Gangaparameshwari.D",
		isSolo: true,
		title: "Data Archeologist",
		github: "https://github.com/Gangaparameshwari07/DATA-ARCHEOLOGIST",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=qlalI8M7qXU",
	},
	{
		team: "Garima",
		submitter: "Garima",
		isSolo: true,
		title: "DataSheriff",
		github: "https://github.com/garimapahwa/Back-to-metadata-hackathon/tree/main/datasheriff",
		deployed: "",
		youtube: "https://www.loom.com/share/dbcef16e30684efbb5e17bae5443b46f",
	},
	{
		team: "Gaurang Bhatt",
		submitter: "Gaurang Bhatt",
		isSolo: true,
		title: "OpenMetadata Observable Connector",
		github: "",
		deployed: "",
		youtube: "https://youtu.be/2K_0dgU3vLg?si=fikMvwIerjgZwlwe",
	},
	{
		team: "Gauransh Arora",
		submitter: "Gauransh Arora",
		isSolo: true,
		title: "ChaosMetadata",
		github: "https://github.com/Gauransh-Arora/ChaosMetaData",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=WuyfCYnanMw",
	},
	{
		team: "Hardik Saini",
		submitter: "Hardik Saini",
		isSolo: true,
		title: "DataPulse",
		github: "https://github.com/yonkosan/collate-ai-sdk/tree/main/solutions/ai_data_sre",
		deployed: "https://wemakedev-hackathon-swart.vercel.app/",
		youtube: "https://youtu.be/CRZctqlzzyw",
	},
	{
		team: "Hardik Saini",
		submitter: "Hardik Saini",
		isSolo: true,
		title: "DataPulse",
		github: "https://github.com/yonkosan/collate-ai-sdk/blob/main/solutions/ai_data_sre/",
		deployed: "https://wemakedev-hackathon-swart.vercel.app/",
		youtube: "https://youtu.be/XJxGSpxoL2k",
	},
	{
		team: "Harish Kotra",
		submitter: "Harish Kotra",
		isSolo: true,
		title: "Living Data DNA Platform",
		github: "https://github.com/harishkotra/living-data-dna-platform",
		deployed: "https://helix-dna-frontend-ojug5k4mta-uc.a.run.app",
		youtube: "https://youtu.be/jrAPNxq0-iw",
	},
	{
		team: "Ishansh Dimaniya",
		submitter: "Ishansh Dimaniya",
		isSolo: true,
		title: "Metadata Change Guard",
		github: "https://github.com/zxsharp/metadata-change-guard",
		deployed: "https://metadata-change-guard-api.vercel.app/#dashboard",
		youtube: "https://youtu.be/P6DmmzJWm2w",
	},
	{
		team: "Jagannath Malode",
		submitter: "Jagannath Malode",
		isSolo: true,
		title: "MetaMind",
		github: "https://github.com/JagannathM05/metamind-openmetadata",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=WYl5lTxJE7w",
	},
	{
		team: "JAYA DUBEY",
		submitter: "JAYA DUBEY",
		isSolo: true,
		title: "OM Incident Bot",
		github: "https://github.com/jaya6400/openmetadata-incident-bot",
		deployed: "https://openmetadata-incident-bot-jd.vercel.app/",
		youtube: "https://www.youtube.com/watch?v=M84QhdeTKWc",
	},
	{
		team: "joeza",
		submitter: "Jay Joshi",
		isSolo: false,
		title: "OpenMetadata-native merge governance and remediation system for data teams",
		github: "https://github.com/jayjoshix/incident-commander",
		deployed: "https://incident-commander.vercel.app/",
		youtube: "https://www.youtube.com/watch?v=KZpedWa9vyA",
	},
	{
		team: "Joseph Thomas Stalin",
		submitter: "Joseph Thomas Stalin",
		isSolo: true,
		title: "FLUX Data Navigator and OpenMetadata MCP",
		github: "https://github.com/Jtss-ux/flux-openmetadata",
		deployed: "https://truthly-blue.vercel.app/",
		youtube: "https://youtu.be/Ked3XL-0fJs",
	},
	{
		team: "Kapil Dethe",
		submitter: "Kapil Dethe",
		isSolo: true,
		title: "DataBuddy",
		github: "https://github.com/kapildethe/databuddy-bot",
		deployed: "https://github.com/kapildethe/databuddy-bot",
		youtube: "https://youtu.be/qOL2LD9t9CI",
	},
	{
		team: "Karan Kumar",
		submitter: "Karan Kumar",
		isSolo: true,
		title: "SentinelX",
		github: "https://github.com/KaranKumar2326/SentinelX",
		deployed: "https://sentinel-x-alpha.vercel.app/",
		youtube: "https://drive.google.com/file/d/1zTKIaCkUtCgRroeRu0ImeFZ4AD12bpOS/view?usp=sharing",
	},
	{
		team: "Keerthivasan S V",
		submitter: "Keerthivasan S V",
		isSolo: true,
		title: "Autonomous RCA Engine",
		github: "https://github.com/Keerthivasan-Venkitajalam/RCA-Engine",
		deployed: "https://rca-engine.vercel.app/",
		youtube: "https://youtu.be/oLtkqEuJ3qw",
	},
	{
		team: "Krishna Srivastava",
		submitter: "Krishna Srivastava",
		isSolo: true,
		title: "Pipeline Autopsy",
		github: "https://github.com/Krishna41357/FixFlow",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=CoTgVXRByfQ",
	},
	{
		team: "Lekan Bams",
		submitter: "Lekan Bams",
		isSolo: true,
		title: "n8n-nodes-openmetadata is the first n8n community node for OpenMetadata, brin...",
		github: "https://github.com/lekanbams/n8n-nodes-openmetadata",
		deployed: "https://www.npmjs.com/package/n8n-nodes-openmetadata",
		youtube: "https://youtu.be/tSy1EF3cE-s",
	},
	{
		team: "LEO Vinayaka SOLO",
		submitter: "Leo Vinayaka",
		isSolo: false,
		title: "MetaWatch",
		github: "https://github.com/Vinayaka5/MetaWatch-/tree/main",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=HXMeiJy8uTw",
	},
	{
		team: "Lineage Whisperer (Big Mara - Solo)",
		submitter: "Big Mara",
		isSolo: false,
		title: "Lineage Whisperer",
		github: "https://maracodez.github.io/Whisperer/",
		deployed: "https://whisperer-gold.vercel.app/",
		youtube: "https://youtube.com/shorts/D4zFyunn1gc?si=D3zUCXi889fUPpAX",
	},
	{
		team: "Mahboob Alam",
		submitter: "Mahboob Alam",
		isSolo: true,
		title: "A",
		github: "https://github.com/Mahboob-A/Datalineage-Doctor/",
		deployed: "https://dldoctor.app/",
		youtube: "https://www.youtube.com/watch?v=p9yGq0KsWhw",
	},
	{
		team: "Manav",
		submitter: "Manav",
		isSolo: true,
		title: "This framework uses a meta-learning model to classify the current regime of t",
		github: "https://github.com/manavmax/Bitcoin-Alpha-System",
		deployed: "",
		youtube: "",
	},
	{
		team: "Manish Kumar",
		submitter: "Manish Kumar",
		isSolo: true,
		title: "OpenMetadata Sync",
		github: "https://github.com/pardhan03/openmetadata-sync-action",
		deployed: "",
		youtube: "https://www.youtube.com/shorts/OIe0VhEFeyk",
	},
	{
		team: "Megh Shah",
		submitter: "Megh Shah",
		isSolo: true,
		title: "This submission focuses on contributing directly to the OpenMetadata platform",
		github: "https://github.com/Megh-Shah-08/OpenMetadata",
		deployed: "",
		youtube: "",
	},
	{
		team: "Metagaurd",
		submitter: "Akash Mohan",
		isSolo: false,
		title: "MetaGuard",
		github: "https://github.com/Akash-How/MetaGuard",
		deployed: "https://meta-guard-puce.vercel.app/",
		youtube: "https://www.youtube.com/watch?v=YWe-KiMRyRg",
	},
	{
		team: "MetaMind AI",
		submitter: "Arijit Ratan Patra",
		isSolo: false,
		title: "MetaBot",
		github: "https://github.com/Arijit-x/metabot.git",
		deployed: "https://incomparable-custard-b2e11e.netlify.app/",
		youtube: "https://youtu.be/3kHBw52FLYg?si=z8gdZy-af-M4bDih",
	},
	{
		team: "MetaMinersAI",
		submitter: "Nabarup Ghosh",
		isSolo: false,
		title: "The OpenMetadata VS Code Extension bridges the gap between data discovery and...",
		github: "https://github.com/Nabarup1/openmetadata-ide/",
		deployed: "https://marketplace.visualstudio.com/items?itemName=Nabarup.openmetadata-hackathon",
		youtube: "https://youtu.be/yDU8yzPppHk",
	},
	{
		team: "Mohammad Arbaz Khilji",
		submitter: "Arbaz",
		isSolo: false,
		title: "MetaCopilot",
		github: "https://github.com/arbaznova/MetaCopilot-main",
		deployed: "",
		youtube: "https://youtu.be/rxu71QeLKpM",
	},
	{
		team: "Mohit Vijay Jeswani",
		submitter: "Mohit Vijay Jeswani",
		isSolo: true,
		title: "For this hackathon, my \"project\" was directly extending OpenMetadata's core a",
		github: "",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=8KB0qq0n434",
	},
	{
		team: "Muhammad Hassaan Saleem",
		submitter: "Muhammad Hassaan Saleem",
		isSolo: true,
		title: "PR Contributions",
		github: "",
		deployed: "",
		youtube: "https://www.loom.com/share/1daadbf0ab334070bd5c5a2c94abc31d",
	},
	{
		team: "N DIVIJ",
		submitter: "N DIVIJ",
		isSolo: true,
		title: "Incidere",
		github: "https://github.com/N-45div/Incidere",
		deployed: "https://incidere.vercel.app",
		youtube: "https://youtu.be/Bl5vtybK9X4",
	},
	{
		team: "Ndubuisi Nwankpa",
		submitter: "Ndubuisi Nwankpa",
		isSolo: true,
		title: "OpenMetadata AI Gateway",
		github: "https://github.com/cyber-ND/openmetadata-ai-gateway.git",
		deployed: "https://openmetadata-ai-gateway.onrender.com/swagger/",
		youtube: "https://www.loom.com/share/8582252e7dcd4ba0a098c2c9bae843fb",
	},
	{
		team: "NextDev",
		submitter: "Riddhi Jathar",
		isSolo: false,
		title: "OpenMetadata for VS Code",
		github: "https://github.com/riddhij-7/openmetadata-vscode",
		deployed: "https://github.com/riddhij-7/openmetadata-vscode/releases/tag/v0.0.1",
		youtube: "https://youtu.be/yzAoi_9kdmo",
	},
	{
		team: "NextGen Devs",
		submitter: "Manas Dutta",
		isSolo: false,
		title: "OpenBlame",
		github: "https://github.com/manasdutta04/openblame",
		deployed: "https://pypi.org/project/openblame/",
		youtube: "https://youtu.be/DWiB1ZtTFXk",
	},
	{
		team: "Nihaal",
		submitter: "Nihaal",
		isSolo: true,
		title: "Steward Copilot",
		github: "https://github.com/nerdylua/steward-copilot",
		deployed: "https://steward-copilot.vercel.app/",
		youtube: "https://youtu.be/pXpyd59oaiQ",
	},
	{
		team: "Nitin Rajpoot",
		submitter: "Nitin Rajpoot",
		isSolo: true,
		title: "Implementation of HTTPS/SSL support for the Apache Druid connector",
		github: "https://github.com/Nitin2332/OpenMetadata",
		deployed: "",
		youtube: "https://youtu.be/b37XivIhcag",
	},
	{
		team: "NoisyBoy",
		submitter: "Uday Dolas",
		isSolo: false,
		title: "TalentifyAI",
		github: "https://github.com/noisyboy08/Talentify-AI.git",
		deployed: "https://talentify-ai-plum.vercel.app/",
		youtube: "https://youtu.be/-PUdZrONB90",
	},
	{
		team: "Oscar Kandir",
		submitter: "Oscar Kandir",
		isSolo: true,
		title: "Chronos turns a 30-60 minute root-cause investigation for failing OpenMetadat...",
		github: "https://github.com/oscarosk/chronos-openmetadata",
		deployed: "",
		youtube: "https://youtu.be/THHkBzvL3l8",
	},
	{
		team: "P Rachel Nishika",
		submitter: "P Rachel Nishika",
		isSolo: true,
		title: "Metadata Bot",
		github: "https://github.com/nishika701/metadata-bot.git",
		deployed: "",
		youtube: "https://youtu.be/ZkPjPddFPIY",
	},
	{
		team: "Pavithra Ebbali",
		submitter: "Pavithra Ebbali",
		isSolo: true,
		title: "MetaShield",
		github: "https://github.com/PavithraEbbali/metashield",
		deployed: "",
		youtube: "https://youtu.be/5PXFRkBIX9g",
	},
	{
		team: "Photons",
		submitter: "Anish Udupa",
		isSolo: false,
		title: "DQ-Agent",
		github: "https://github.com/Photon079/Openmetaadatahack",
		deployed: "https://openmetaadatahack.vercel.app/",
		youtube: "https://www.youtube.com/watch?v=NLBwnuD5I4k",
	},
	{
		team: "PRATYAKSHYA MISHRA",
		submitter: "PRATYAKSHYA MISHRA",
		isSolo: true,
		title: "Every day, analysts and managers receive Excel files with zero context",
		github: "https://github.com/pratyakshyamishra43-coder/MetaLens",
		deployed: "https://metalens-production.up.railway.app",
		youtube: "https://youtu.be/Rl72cmrnrc8",
	},
	{
		team: "Puneet Kumar",
		submitter: "Puneet Kumar",
		isSolo: true,
		title: "MetaVerdax Agent",
		github: "https://github.com/PuneetKumar1790/MetaVerdax",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=t0JEXYOQWjY",
	},
	{
		team: "pup",
		submitter: "manisai gaddam",
		isSolo: false,
		title: "Datasential",
		github: "https://github.com/manisaigaddam/datasential",
		deployed: "https://datasential.duckdns.org/",
		youtube: "https://youtu.be/l_7dPLDKtS8",
	},
	{
		team: "Purbayan Pramanik",
		submitter: "Purbayan Pramanik",
		isSolo: true,
		title: "Automated repair suggestions for failed OpenMetadata Data Quality checks",
		github: "https://github.com/PPRAMANIK62/openmetadata-dq-autofix",
		deployed: "",
		youtube: "https://youtu.be/rz_JBwoxVCI",
	},
	{
		team: "Rajat Sharma",
		submitter: "Rajat Sharma",
		isSolo: true,
		title: "A pixel-art detective game where the crime scene is an OpenMetadata catalog",
		github: "https://github.com/git-pixel22/catalog-noir",
		deployed: "https://catalog-noir.onrender.com/",
		youtube: "https://www.youtube.com/watch?v=4fdr179DjmA",
	},
	{
		team: "RICARDO ALMEIDA",
		submitter: "RICARDO ALMEIDA",
		isSolo: true,
		title: "OpenMetadata MCP Server++",
		github: "https://github.com/pt-act/OpenMetadata",
		deployed: "",
		youtube: "https://youtu.be/-3SLF81b1T0",
	},
	{
		team: "RITURAJ DEY",
		submitter: "RITURAJ DEY",
		isSolo: true,
		title: "DataSheriff",
		github: "https://github.com/Rituraj-13/DataSheriff",
		deployed: "https://datasheriff.riturajdey01.workers.dev/",
		youtube: "https://youtu.be/FJjLcWuaQ0M",
	},
	{
		team: "RKO",
		submitter: "Blessings Wanjiku",
		isSolo: false,
		title: "MetaMind",
		github: "https://github.com/Nosh-thee-techy/metamind",
		deployed: "https://metamind-zeta.vercel.app/",
		youtube: "https://youtu.be/7pQaoujYF1U",
	},
	{
		team: "Roman Medvedev",
		submitter: "Roman Medvedev",
		isSolo: true,
		title: "OpenMetadata CLI",
		github: "https://github.com/romamo/openmetadata-cli",
		deployed: "https://crates.io/crates/openmetadata-cli",
		youtube: "https://youtu.be/5MBHXG8exNI",
	},
	{
		team: "Sachin C",
		submitter: "Sachin C",
		isSolo: true,
		title: "FLUX",
		github: "https://github.com/sachinc21/flux-oracle.git",
		deployed: "",
		youtube: "https://youtu.be/8iA1FLv3LDY",
	},
	{
		team: "Sahil Ahuja",
		submitter: "Sahil Ahuja",
		isSolo: true,
		title: "Implemented scalable Role search support in the OpenMetadata repository by ad...",
		github: "",
		deployed: "",
		youtube: "https://youtu.be/Z5zAQ7axxwM",
	},
	{
		team: "Sam Zhijian",
		submitter: "Sam Zhijian",
		isSolo: true,
		title: "Autonomous Data Guardian",
		github: "https://github.com/Autonomous-Data-Guardian/autonomous-data-guardian",
		deployed: "",
		youtube: "https://youtu.be/4bavI-u5hIs",
	},
	{
		team: "Serendipity",
		submitter: "Ishaan",
		isSolo: false,
		title: "We've made a production-ready GitHub Action for data impact analysis",
		github: "https://github.com/Ishaan2053/openmetadata-data-impact-action",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=iVBs-KyPHCE",
	},
	{
		team: "Shiva",
		submitter: "Shiva",
		isSolo: true,
		title: "omctl is a developer-first CLI for OpenMetadata that brings metadata discover...",
		github: "https://github.com/shivakumar2006/OpenMetaDataCommandLineTool",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=_d4AdwyXWLw&t=1s",
	},
	{
		team: "Shivansh Bagga",
		submitter: "Shivansh Bagga",
		isSolo: true,
		title: "DataPulse",
		github: "https://github.com/baggashivansh/DataPulse-Real-Time-Data-Risk-Radar",
		deployed: "https://github.com/baggashivansh/DataPulse-Real-Time-Data-Risk-Radar",
		youtube: "",
	},
	{
		team: "Shruti Sharma",
		submitter: "Shruti Sharma",
		isSolo: true,
		title: "ChronosData AI",
		github: "https://github.com/shrutisharma-sh/ChronsData.git",
		deployed: "",
		youtube: "https://youtu.be/BNtLAT99siE?si=yEYKHE-ul8lg7bhd",
	},
	{
		team: "Shubham Jaiswal",
		submitter: "Shubham Jaiswal",
		isSolo: true,
		title: "SMART DATASET ONBOARDING ASSISTANT",
		github: "https://github.com/Shubham-Jaiswal5414/Smart_Onboarding",
		deployed: "https://idyllic-travesseiro-85eae6.netlify.app/",
		youtube: "https://youtu.be/PShYRO9d2Sk",
	},
	{
		team: "shubham oulkar",
		submitter: "shubham oulkar",
		isSolo: true,
		title: "A Slack app that lets your team search for data without ever leaving their chat",
		github: "https://github.com/ShubhamOulkar/OpenMetadata/tree/slack-app",
		deployed: "",
		youtube: "https://youtu.be/DFNUCfDiU9g",
	},
	{
		team: "Sigireddy Viswesh",
		submitter: "Sigireddy Viswesh",
		isSolo: true,
		title: "It's called Blast Radius (I made it up)",
		github: "https://github.com/Viswesh934/Blast-Radius",
		deployed: "",
		youtube: "https://youtu.be/dmMILKhFBlw",
	},
	{
		team: "Slice Of Code",
		submitter: "Sumit Chawla",
		isSolo: false,
		title: "ometa-diff adds metadata version-diff intelligence to OpenMetadata — giving A...",
		github: "https://github.com/SamChawla/ometa-diff",
		deployed: "https://pypi.org/project/ometa-diff/",
		youtube: "https://youtu.be/eskLxI-GpJk",
	},
	{
		team: "Solomon Emmanuel Thompson I",
		submitter: "Solomon Emmanuel Thompson I",
		isSolo: true,
		title: "AutoSteward AI",
		github: "https://github.com/Prototype4988/AutoStewardAI",
		deployed: "",
		youtube: "https://youtu.be/5aFqfzyFa1g",
	},
	{
		team: "Somehow",
		submitter: "Aditi Singh",
		isSolo: false,
		title: "The Problem Modern data ecosystems are inherently fragmented",
		github: "https://github.com/aditisingh02/meridian",
		deployed: "https://www.meridian-ai.xyz/",
		youtube: "https://youtu.be/4QFpf4FTF7s",
	},
	{
		team: "Spambots",
		submitter: "Janesh Kapoor",
		isSolo: false,
		title: "MetaTree brings OpenMetadata to the exact places where data decisions are mad...",
		github: "https://github.com/JaneshKapoor/metatree",
		deployed: "https://github.com/JaneshKapoor/metatree/releases/tag/v0.1.0",
		youtube: "https://drive.google.com/drive/folders/1Gvo2AKaEWNcFDnRA6FQrxY3Fu0ACzL5I",
	},
	{
		team: "Srikar Polisetty",
		submitter: "Srikar Polisetty",
		isSolo: true,
		title: "CatalogLens",
		github: "https://github.com/srikarpolisetty-svg/CatalogLens",
		deployed: "",
		youtube: "https://youtu.be/_asu3G1zVzk",
	},
	{
		team: "Sushant jain",
		submitter: "Sushant jain",
		isSolo: true,
		title: "It's 3 a.m",
		github: "https://github.com/Sushant6095/Casusal-ops-metadata",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=RY17vOJCn_A",
	},
	{
		team: "Syed Md Mihan Chistie",
		submitter: "Syed Md Mihan Chistie",
		isSolo: true,
		title: "Metal",
		github: "https://github.com/Mihan786Chistie/metal-server, https://github.com/Mihan786Chistie/metal-app",
		deployed: "",
		youtube: "https://youtu.be/kvRApJntQBY",
	},
	{
		team: "Talha Amjad",
		submitter: "Talha Amjad",
		isSolo: true,
		title: "Talha Amjad project",
		github: "",
		deployed: "",
		youtube: "https://www.loom.com/share/e02b4daba764483782f99a52f6afe915",
	},
	{
		team: "Team Aryabit",
		submitter: "Dhyan S Kanapadi",
		isSolo: false,
		title: "DataSentinel",
		github: "https://github.com/Dhyan-S-Kanapadi/DataSentinel",
		deployed: "",
		youtube: "",
	},
	{
		team: "Team Light Mode",
		submitter: "Mohit Upadhyay",
		isSolo: false,
		title: "Goal: Chronos Lens is built to close the gap between metadata and execution b",
		github: "https://github.com/anuj123upadhyay/chronos-lens-openmetadata",
		deployed: "https://github.com/anuj123upadhyay/chronos-lens-openmetadata",
		youtube: "https://www.youtube.com/watch?v=qrSK0G8kiWk",
	},
	{
		team: "Team Rakshak",
		submitter: "Pavan kumar",
		isSolo: false,
		title: "What We Built",
		github: "https://github.com/Pavankumar07s/OpenMetaData.git",
		deployed: "",
		youtube: "https://youtu.be/lyjH9JaDIIU",
	},
	{
		team: "TechTrek",
		submitter: "Manikant Kella",
		isSolo: false,
		title: "Lighthouse turns OpenMetadata into a visual diagnostic console",
		github: "https://github.com/Manikant92/lighthouse",
		deployed: "",
		youtube: "https://youtu.be/YSdcuYog-y8",
	},
	{
		team: "Techverse",
		submitter: "BHUVANESH S",
		isSolo: false,
		title: "I Data Doctor",
		github: "https://github.com/bhuviguru/ai_datadoctor.git",
		deployed: "",
		youtube: "https://youtube.com/shorts/pNAhlA-dvYU?si=4HJhcNvF7ns385ip",
	},
	{
		team: "Temiloluwa Valentine",
		submitter: "Temiloluwa Valentine",
		isSolo: true,
		title: "African ML engineers are building models with the wrong data",
		github: "https://github.com/Valentinetemi/afrigen-solo",
		deployed: "https://afrigen-gtht.onrender.com",
		youtube: "https://youtu.be/nggaI87IDts",
	},
	{
		team: "The Boys",
		submitter: "GAGAN RAO K",
		isSolo: false,
		title: "DataNexus AI Chat",
		github: "https://github.com/ganeshark04/datanexus-ai-chat",
		deployed: "",
		youtube: "https://youtu.be/QzkgCAnJK3A",
	},
	{
		team: "The Mavericks",
		submitter: "Guna Palanivel",
		isSolo: false,
		title: "We started from a small scaffold so the repo had a clear shape early",
		github: "https://github.com/GunaPalanivel/openmetadata-mcp-agent",
		deployed: "",
		youtube: "https://drive.google.com/drive/folders/1jzYpPLm9WlYorKzX6Uky8Qp_udOTBKwS?usp=sharing",
	},
	{
		team: "Thrusters",
		submitter: "Kartik",
		isSolo: false,
		title: "Auto-Medic",
		github: "https://github.com/karttikjangid/CI-CD-gatekeeper",
		deployed: "https://github.com/karttikjangid/CI-CD-gatekeeper/pull/5",
		youtube: "https://youtu.be/UqUxn1vLjXo",
	},
	{
		team: "Tomoya Hatanaka",
		submitter: "Tomoya Hatanaka",
		isSolo: true,
		title: "This project provides an MCP (Model Context Protocol) server that connects AI",
		github: "https://github.com/dorakingx/openmetadata-mcp-server",
		deployed: "",
		youtube: "https://youtu.be/osT_znkVsK0",
	},
	{
		team: "udi ngethe",
		submitter: "udi ngethe",
		isSolo: true,
		title: "Data catalogs are full of valuable metadata, but most of it goes unused",
		github: "https://github.com/thisyearnofear/databard",
		deployed: "https://databard.thisyearnofear.com/",
		youtube: "https://youtu.be/saUAYMIqjHU",
	},
	{
		team: "UNO",
		submitter: "Abhishek Jain",
		isSolo: false,
		title: "OpenMetadata CLI #26649  and GitHub Action: \"What Breaks If I Change This?\" #...",
		github: "https://github.com/abhiiiesh/OpenMetaCLI.git",
		deployed: "",
		youtube: "https://github.com/abhiiiesh/OpenMetaGithubAction.git",
	},
	{
		team: "unoplat code confluence",
		submitter: "Jay Ghiya",
		isSolo: false,
		title: "Developing a custom connector for openmetadata for the only missing metadata ...",
		github: "https://github.com/unoplat/unoplat-code-confluence",
		deployed: "",
		youtube: "https://www.youtube.com/watch?v=Z0HojucTnvQ&feature=youtu.be",
	},
	{
		team: "Vedant balachandra",
		submitter: "Vedant Balachandra",
		isSolo: true,
		title: "Sentari",
		github: "https://github.com/vedant45/Sentari",
		deployed: "",
		youtube: "https://youtu.be/-RLgNZ1R5J4",
	},
	{
		team: "Vijay Prasad",
		submitter: "Vijay Prasad",
		isSolo: true,
		title: "I built VAANI , it is  an intelligent observability and governance layer for ...",
		github: "https://github.com/V-2007-P/openmetadata_project.gitx",
		deployed: "https://openmetadata-project.onrender.com",
		youtube: "https://youtu.be/dmvxQPO292A?si=MoFGSNJbckhuMQvC",
	},
	{
		team: "Vivek Bardava",
		submitter: "Vivek Bardava",
		isSolo: true,
		title: "AI Data Analyst",
		github: "https://github.com/VivekBardava-OG/Project-AI-Data-Analyst-Agent.git",
		deployed: "",
		youtube: "https://youtu.be/AqxX1g8sgyI?si=u0HEXLkKeRdKKLD0",
	},
	{
		team: "Vrushabh K. Zade",
		submitter: "Vrushabh Zade",
		isSolo: false,
		title: "Neo Catalog",
		github: "https://github.com/vrushabhzade/Neo-catalog.git",
		deployed: "https://neo-assistant-603698625720.us-central1.run.app",
		youtube: "https://youtu.be/1gGgeTmUliY",
	},
	{
		team: "Whiplash",
		submitter: "Swayam Bansal",
		isSolo: false,
		title: "OpenMetadata",
		github: "https://github.com/swymbnsl/metalens.git",
		deployed: "https://metalens.swymbnsl.com",
		youtube: "https://ytvideos.swymbnsl.com/metalens",
	},
	{
		team: "XYRO",
		submitter: "Praveen Chaudhary",
		isSolo: false,
		title: "PYQs to help college students",
		github: "https://github.com/chaudharypraveennn/project-AKTU.git",
		deployed: "https://solvvr.vercel.app/",
		youtube: "",
	},
	{
		team: "Yash Agarwal",
		submitter: "Yash Agarwal",
		isSolo: true,
		title: "DataPulse",
		github: "https://github.com/yash-agarwa-l/datapulse",
		deployed: "",
		youtube: "https://youtu.be/J01ha9EZw_8",
	},
	{
		team: "Yash Pawar",
		submitter: "Yash Pawar",
		isSolo: true,
		title: "Data teams break downstream pipelines daily because SQL changes are merged wi...",
		github: "https://github.com/yashpawarrr/openmetadata_hackathon.git",
		deployed: "",
		youtube: "https://youtu.be/d4xZxU9N2Ck",
	},
	{
		team: "Yash Sainani",
		submitter: "Yash Sainani",
		isSolo: true,
		title: "or this hackathon, my project was directly extending OpenMetadata's core arch",
		github: "",
		deployed: "",
		youtube: "https://youtu.be/Rw_nyPfRZX0",
	},
	{
		team: "Yolo",
		submitter: "Charan Tej",
		isSolo: false,
		title: "public unified life safety and survelience engine",
		github: "https://github.com/SajalDevX/PESS",
		deployed: "",
		youtube: "https://youtu.be/kOw5B9dvAXY",
	},
	{
		team: "Zoora",
		submitter: "Arbaz",
		isSolo: false,
		title: "MetaCopilot",
		github: "https://github.com/arbaznova/MetaCopilot-main",
		deployed: "",
		youtube: "https://youtu.be/rxu71QeLKpM",
	},
];

type PrContributor = {
	name: string;
	team: string;
	isSolo: boolean;
	prLinks: string[];
};

const prContributors: PrContributor[] = [
	{
		name: "Muhammad Hassaan Saleem",
		team: "Muhammad Hassaan Saleem",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27495", "https://github.com/open-metadata/OpenMetadata/pull/27286", "https://github.com/open-metadata/OpenMetadata/pull/27225", "https://github.com/open-metadata/OpenMetadata/pull/27717", "https://github.com/open-metadata/OpenMetadata/pull/27508"],
	},
	{
		name: "Yash Sainani",
		team: "Yash Sainani",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27738", "https://github.com/open-metadata/OpenMetadata/pull/27514", "https://github.com/open-metadata/OpenMetadata/pull/27512", "https://github.com/open-metadata/OpenMetadata/pull/27330", "https://github.com/open-metadata/OpenMetadata/pull/27353"],
	},
	{
		name: "Mohit Vijay Jeswani",
		team: "Mohit Vijay Jeswani",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27573", "https://github.com/open-metadata/OpenMetadata/pull/27645", "https://github.com/open-metadata/OpenMetadata/pull/27733", "https://github.com/open-metadata/OpenMetadata/pull/27735"],
	},
	{
		name: "Talha Amjad",
		team: "Talha Amjad",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27453", "https://github.com/open-metadata/OpenMetadata/pull/27488", "https://github.com/open-metadata/OpenMetadata/pull/27478", "https://github.com/open-metadata/OpenMetadata/pull/27589"],
	},
	{
		name: "Harish Kotra",
		team: "Harish Kotra",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27359", "https://github.com/open-metadata/OpenMetadata/pull/27590", "https://github.com/open-metadata/openmetadata-helm-charts/pull/500", "https://github.com/open-metadata/OpenMetadata/pull/27360"],
	},
	{
		name: "JAYA DUBEY",
		team: "JAYA DUBEY",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27521", "https://github.com/open-metadata/openmetadata-site/pull/341"],
	},
	{
		name: "Karthik Rajan M R",
		team: "Karthik Rajan M R",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27505", "https://github.com/open-metadata/OpenMetadata/pull/27460"],
	},
	{
		name: "Megh Shah",
		team: "Megh Shah",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27465", "https://github.com/open-metadata/OpenMetadata/pull/27633"],
	},
	{
		name: "Shruti Sharma",
		team: "Shruti Sharma",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27364"],
	},
	{
		name: "Darshan Rajput",
		team: "Darshan3690",
		isSolo: false,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27143"],
	},
	{
		name: "Joseph Thomas Stalin",
		team: "Joseph Thomas Stalin",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27628"],
	},
	{
		name: "Temiloluwa Valentine",
		team: "Temiloluwa Valentine",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27736"],
	},
	{
		name: "Gaurang Bhatt",
		team: "Gaurang Bhatt",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27317"],
	},
	{
		name: "Sahil Ahuja",
		team: "Sahil Ahuja",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27556"],
	},
	{
		name: "Nitin Rajpoot",
		team: "Nitin Rajpoot",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27634"],
	},
	{
		name: "Keerthivasan S V",
		team: "Keerthivasan S V",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27741"],
	},
	{
		name: "Yash Agarwal",
		team: "Yash Agarwal",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27035"],
	},
	{
		name: "Shivansh Bagga",
		team: "Shivansh Bagga",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/issues/27004"],
	},
	{
		name: "Piyush Kumar",
		team: "Deployed on Friday",
		isSolo: false,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27516"],
	},
	{
		name: "Roshan",
		team: "Roshan Kumar",
		isSolo: false,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27607"],
	},
	{
		name: "Yashwanth Sai Chennupalli",
		team: "Yashwanth Sai Chennupalli",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27734"],
	},
	{
		name: "Abhay Singh",
		team: "Abhay Singh",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27553"],
	},
	{
		name: "Aditya Kumar Puri",
		team: "Aditya Kumar Puri",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27743"],
	},
	{
		name: "Sajal Chandhoke",
		team: "dontcode",
		isSolo: false,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27744"],
	},
	{
		name: "Manav",
		team: "Manav",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27727"],
	},
	{
		name: "David Abdiel Mamani Chuquimamani",
		team: "David Abdiel Mamani Chuquimamani",
		isSolo: true,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/pull/27529"],
	},
	{
		name: "Nabarup Ghosh",
		team: "MetaMinersAI",
		isSolo: false,
		prLinks: ["https://github.com/open-metadata/OpenMetadata/issues/26650"],
	},
];

export { winningProjects, submittedProjects, prContributors };
export type { SubmittedProject, PrContributor };
