const winningProjects = [
	{
		teamName: "CipherX",
		projectTitle: "DealDesk-Tambo",
		description:
			"An AI-native contract workspace where the UI adapts to what you're trying to do: assess risk, refine clauses, clarify definitions, and track obligations. Features RiskRadar for category risk visualization, ClauseTuner for interactive clause refinement, ExtractionChecklist for obligations tracking, and KnowledgeBank for definitions glossary.",
		githubLink: "https://github.com/wafflebytes/DealDesk-Tambo",
		deployedLink: "https://deal-desk-tambo.vercel.app",
		youtubeEmbed: "https://www.youtube.com/embed/V0RTi8uorJM",
		prize: "1st Prize",
	},
	{
		teamName: "Akinkunmi",
		projectTitle: "Fireflow",
		description:
			"AI-powered n8n alternative where you can create complex workflows using natural language. Tambo powers the AI chat interface for the workflow builder. Users describe workflows in natural language, and Tambo's AI generates the visual workflow nodes and connections automatically.",
		githubLink: "https://github.com/akinloluwami/fireflow",
		deployedLink: "https://fireflow.run",
		youtubeEmbed: "https://www.youtube.com/embed/WUNEUTLr7Zo",
		prize: "2nd Prize",
	},
	{
		teamName: "MergeConflict",
		projectTitle: "Brilliant",
		description:
			"An intelligent calendar application with conversational AI capabilities, built with React and integrated with Google Calendar. Schedule, manage, and reorganize your events naturally through chat. Uses Tambo as the full-stack AI orchestration layer with custom tools for calendar operations and GenerativeForm for interactive forms.",
		githubLink: "https://github.com/BeeBombshell/brilliant",
		deployedLink: "https://brilliant.beebombshell.com",
		youtubeEmbed: "https://www.youtube.com/embed/guKonk9apTM",
		prize: "3rd Prize",
	},
];

const topProjects = [
	{
		teamName: "Aymaan Pathan",
		projectTitle: "InfraPilot",
		description:
			"A Generative Kubernetes Dashboard where the UI is created dynamically based on user commands. Using Tambo, the app converts natural language inputs like \"show pods\", \"explain errors\", or \"compare CPU usage\" into interactive UI components such as tables, metrics panels, and log viewers.",
		githubLink: "https://github.com/AymaanPathan/InfraPilot",
		youtubeEmbed: "https://www.youtube.com/embed/8QPMGPDVDNY",
	},
	{
		teamName: "Vidit Maheshwari",
		projectTitle: "SchemaAI",
		description:
			"Supabase Schema Visualizer - a developer tool that makes working with database schemas simple and intuitive. Using Tambo's Generative UI, the AI decides which React components to render based on intent, from visual schema canvas to data tables, charts, or metadata views.",
		githubLink: "https://github.com/vidit-maheshwari/SchemaAI",
		deployedLink: "https://schema-ai-seven.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/DoGv47j3qEo",
	},
	{
		teamName: "Pravesh",
		projectTitle: "Skilldebt.ai",
		description:
			"An AI-powered tool that takes your resume, builds a skill radar chart, analyzes your skill decay, does a Risk Audit and provides an Upgrade Path. Uses Tambo SDK to generate four dynamic Card Views for Skill Radar, Timeline Decay, Risk Audit, and Upgrade Paths.",
		githubLink: "https://github.com/Pravesh-Sudha/ui-strikes-back",
		deployedLink: "https://my-repo-8k7lhiaxb-pravesh-sudhas-projects.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/ItTKixXJF2I",
	},
	{
		teamName: "Balu Chandrasekhar Tirupati",
		projectTitle: "SocialStudio",
		description:
			"An AI platform for Instagram Reels & YouTube creators. Upload one reel, get everything done in one place — subtitles, thumbnails, captions, descriptions, planning and much more. Eight generative components and four calendar tools are registered with Tambo.",
		githubLink: "https://github.com/Balusekhar/socialstudio_tamboai",
		deployedLink: "https://socialstudio.balutirupati.me/",
		youtubeEmbed: "https://www.youtube.com/embed/KwIZm1k1Q3o",
	},
	{
		teamName: "Ayush Shrotriya",
		projectTitle: "DeathStarOps",
		description:
			"A Star Wars-themed, real-time Kubernetes monitoring dashboard featuring an embedded AI DevOps assistant. Engineers can ask natural language questions like \"Why is the payment-service pod crashing?\" and the AI will fetch live logs, analyze events, and suggest fixes immediately.",
		githubLink: "https://github.com/ayushsgit/DeathStarOps",
		deployedLink: "https://deathstarops.netlify.app/",
		youtubeEmbed: "https://www.youtube.com/embed/w42zsEMnY0g",
	},
	{
		teamName: "T Sharan Raj",
		projectTitle: "MediHealth CRM",
		description:
			"A comprehensive hospital CRM with an integrated AI assistant powered by Tambo AI, delivering intelligent healthcare management through generative UI/UX. Features AI-driven patient vitals display, doctor prescriptions, and lab result cards.",
		githubLink: "https://github.com/sharanrajt/medihealth-crm",
		deployedLink: "https://medihealth-crm.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/CbwyeRxpwEo",
	},
	{
		teamName: "Ctrl",
		projectTitle: "Parental Handbook",
		description:
			"An AI-powered Parental Log Application that tracks sleep, meals, moods, milestones, health symptoms, and routines. Features 15 registered Tambo components and 20+ AI tools for comprehensive parenting support from newborn to late teenage years.",
		githubLink: "https://github.com/geoffrey-anto/parental-log-tambo/",
		deployedLink: "https://parental-log-tambo.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/bWvThQlytG4",
	},
	{
		teamName: "Innovators",
		projectTitle: "Prompt Edit Studio",
		description:
			"An in-browser, Generative UI-powered photo editing experience where users describe the aesthetic they want and receive tool recommendations, exact parameters, and step-by-step guidance while staying fully in creative control.",
		githubLink: "https://github.com/silvrfur/prompt-edit",
		deployedLink: "https://prompt-edit-studio.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/TsHn2JCATbU",
	},
	{
		teamName: "Team Dark Mode",
		projectTitle: "Terminus",
		description:
			"Tambo AI powered Generative UI Terminal that replaces traditional terminal output with rich, interactive React components. Features 7 GenUI components, 10 backend tools, secure IPC bridge, and voice input via useTamboVoice.",
		githubLink: "https://github.com/anuj123upadhyay/terminus",
		youtubeEmbed: "https://www.youtube.com/embed/_jMZ1NZNU6c",
	},
	{
		teamName: "Tushar Khatri",
		projectTitle: "Athena AI",
		description:
			"A context-aware productivity copilot that turns natural language into live, app-specific interfaces. Unifies Gmail, Notion, Calendar, Spotify, and GitHub in one place with 46 custom Tambo components and MCP integration for real actions.",
		githubLink: "https://github.com/tusharkhatriofficial/athena-ai",
		deployedLink: "https://athena-ai.tusharkhatri.in/",
		youtubeEmbed: "https://www.youtube.com/embed/9LOudz-VLz8",
	},
	{
		teamName: "Ayush Kumar Singh",
		projectTitle: "ClawBoard",
		description:
			"A better dashboard for managing and chatting with your OpenClaw instances, where OpenClaw handles assistant reasoning/actions and Tambo renders interactive UI components inline in the same conversation.",
		githubLink: "https://github.com/ayush-that/clawboard-app",
		deployedLink: "https://cb.ayushworks.com/",
		youtubeEmbed: "https://www.youtube.com/embed/zNM0L0SO1K8",
	},
	{
		teamName: "Solo",
		projectTitle: "Galactic Command Center",
		description:
			"A fully functional, space-themed AI dashboard that demonstrates Generative UI. Users interact through natural language, and the AI dynamically assembles the interface from a registry of 10+ interactive components.",
		githubLink: "https://github.com/Vikaskumarrr/Galactic-command-center",
		deployedLink: "https://galactic-command-center-rho.vercel.app",
		youtubeEmbed: "https://www.youtube.com/embed/Qm9toQZ6ETY",
	},
	{
		teamName: "StormTroopers",
		projectTitle: "Smart Apartment Management",
		description:
			"A next-generation smart residence UI platform with room-based, immersive digital environments. Features AI-assisted analytics with bar and pie charts, GPU-accelerated WebGL backgrounds, and dual user roles for admin and residents.",
		githubLink: "https://github.com/SanjaySG02/project-tambo",
		deployedLink: "https://projecttambo.netlify.app/",
		youtubeEmbed: "https://www.youtube.com/embed/1hJg411U-6o",
	},
	{
		teamName: "Kumar Nirupam",
		projectTitle: "Tambo Email",
		description:
			"An AI-powered email assistant that lets users manage emails using natural language. Features interactive dashboards, email previews, contact cards, and real backend tools for sending emails and managing contacts.",
		githubLink: "https://github.com/KUMARNiru007/tambo-email",
		deployedLink: "https://tambo-email.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/kC7woWLpyQQ",
	},
	{
		teamName: "Aaditya Srivastava",
		projectTitle: "Tambo Browser",
		description:
			"An AI-enhanced search engine and conversational browser that replaces traditional text-based AI responses with real, interactive UI components. Features 10 workspace views, 5 inline components, and 7 AI tools for a complete research experience.",
		githubLink: "https://github.com/sumionochi/Tambo-Browser-Search-Engine",
		youtubeEmbed: "https://www.youtube.com/embed/_vhuwy30TKA",
	},
	{
		teamName: "Rugpull",
		projectTitle: "Dambo",
		description:
			"An intelligent, conversational data visualization platform designed to visualize raw datasets into interactive insights through natural language. Features infinite collaborative canvas with resize, arrange, and chart fusion capabilities.",
		githubLink: "https://github.com/kymibuilds/dambo",
		deployedLink: "https://dambo-ai.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/1KmF759G1ck",
	},
	{
		teamName: "SOLO",
		projectTitle: "MediFlow",
		description:
			"An AI health assistant that changes its interface based on user needs. Features 15+ registered React components, 9 custom tools, interactive BodyMapper, TrendChart, and MCP integration for cross-referencing patient medications.",
		githubLink: "https://github.com/debjotyms/mediflow",
		deployedLink: "https://mediflow-black.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/S0nwPvBFYrU",
	},
];

const otherProjects: { teamName: string; projectTitle: string; githubLink: string }[] = [
	{ teamName: "SOLO", projectTitle: "PermitPilot", githubLink: "https://github.com/SachinMyadam/agents.md" },
	{ teamName: "Utkarsh Bodele", projectTitle: "Tambo WorkOS", githubLink: "https://github.com/utkarshbodele23/tambo-ai-hackathon" },
	{ teamName: "Nicolas Mondain", projectTitle: "tambook", githubLink: "https://github.com/nicolasmondain/tambook" },
	{ teamName: "Shivansh Bagga", projectTitle: "IntentDesk", githubLink: "https://github.com/baggashivansh/IntentDesk" },
	{ teamName: "Vivek Kumar Keshri", projectTitle: "DSA Mentor AI", githubLink: "https://github.com/vivekkumar04-max/DSA-mentor-ai" },
	{ teamName: "Ganeswar Sahoo", projectTitle: "Tambo UI Generator", githubLink: "https://github.com/ganeswar-sahoo/tambo-ui-generator" },
	{ teamName: "Naba,s striker", projectTitle: "JavaGen & UI-Forge", githubLink: "https://github.com/AbhiDevp151/old-projects" },
	{ teamName: "UNI", projectTitle: "UniTrainer", githubLink: "https://github.com/belocci/UniTrainer" },
	{ teamName: "Think Twice", projectTitle: "DataViz", githubLink: "https://github.com/SpandanM110/DataViz" },
	{ teamName: "MANAS DUTTA", projectTitle: "ReliefOps", githubLink: "https://github.com/manasdutta04/ReliefOps" },
	{ teamName: "Esheshwari Kumari", projectTitle: "PWOA", githubLink: "https://github.com/Esheshwari/PWOA" },
	{ teamName: "Solo", projectTitle: "Tambo Career Platform", githubLink: "https://github.com/subramanidevara/tambo-career-platform" },
	{ teamName: "Munna AK", projectTitle: "AnimeVerse", githubLink: "https://github.com/munna710/web" },
	{ teamName: "SOLO", projectTitle: "OpenCircuit", githubLink: "https://github.com/Joystonm/OpenCircuit" },
	{ teamName: "Harshit Shesh", projectTitle: "Business Solution AI", githubLink: "https://github.com/harshitshesh/Business_Solution-AI" },
	{ teamName: "Rakesh jha", projectTitle: "AI Career Navigator", githubLink: "https://github.com/rakesh0x/career" },
	{ teamName: "Dhrumit Choudhary", projectTitle: "Smart Society AI Assistant", githubLink: "https://github.com/dhrumitcodes/smart-society-ai-assistant" },
	{ teamName: "Darshan Parmar (IdeaFlow)", projectTitle: "IdeaFlow", githubLink: "https://github.com/darshan02parmar/ideaflow" },
	{ teamName: "Mengani Shashank", projectTitle: "PM-AI", githubLink: "https://github.com/Shashank-Mengani/AI-Product-Manager" },
	{ teamName: "Dev Parikh", projectTitle: "Expense sharing platform", githubLink: "https://github.com/Dev0907/TamboAIHackathon" },
	{ teamName: "SOLO", projectTitle: "ChainScope AI", githubLink: "https://github.com/OmkarK97/chainscope-ai" },
	{ teamName: "Team Binary force", projectTitle: "RoastMe AI", githubLink: "https://github.com/santhoshkrishnan-M/RoastMe-AI" },
	{ teamName: "SHASHANT", projectTitle: "Humanity", githubLink: "https://github.com/Shashantkashyap/Humanity" },
	{ teamName: "winners", projectTitle: "FinanceJedi", githubLink: "https://github.com/Roshan-Kumar-Sharma/tambo-ai-finance-jedi" },
	{ teamName: "SOLO/ team name though: difficult", projectTitle: "VibeControl", githubLink: "https://github.com/wildhash/vibe-control" },
	{ teamName: "Samiksha Lambe", projectTitle: "Tambo Resume Bot", githubLink: "https://github.com/samikshalambe/tambo-resume-bot" },
	{ teamName: "AYANA SARKAR", projectTitle: "NOVA OPS", githubLink: "https://github.com/ghosthouse7/nova-ops" },
	{ teamName: "Aditya Verma", projectTitle: "IntentTrace", githubLink: "https://github.com/adit-ya15/IntentTrace" },
	{ teamName: "GAMMA", projectTitle: "Fix-OS", githubLink: "https://github.com/Sanskaragrawal2107/tambo_hackathon" },
	{ teamName: "OutOfBounds", projectTitle: "Command UI", githubLink: "https://github.com/Bhuvan-08/command-ui" },
	{ teamName: "AgniBytes", projectTitle: "Margdarshak", githubLink: "https://github.com/hardik-gexcode/nsf-skill-guide" },
	{ teamName: "uizards", projectTitle: "ShopFlow", githubLink: "https://github.com/pratik-dubey/Shopflow" },
	{ teamName: "team-x", projectTitle: "tamboora", githubLink: "https://github.com/aman99/tamboora" },
	{ teamName: "SOLO", projectTitle: "Generative SQL Viz", githubLink: "https://github.com/Kartikgarg74/generative-sql-viz" },
	{ teamName: "SOLO", projectTitle: "Hackathon Command Center", githubLink: "https://github.com/mohitjeswani01/hackathon-command-center" },
	{ teamName: "Open Devs", projectTitle: "InvoiceAI", githubLink: "https://github.com/ravixalgorithm/invoiceai" },
	{ teamName: "Himanshu Soni", projectTitle: "AutoFlow", githubLink: "https://github.com/h30s/autoflow" },
	{ teamName: "Kaushik Paykoli", projectTitle: "Klay", githubLink: "https://github.com/kaushik0010/klay" },
	{ teamName: "ANKITA SAHU", projectTitle: "Contract Studio", githubLink: "https://github.com/SAHU-01/contract-studio" },
	{ teamName: "Cyprian Kiplangat", projectTitle: "GenUI Playground", githubLink: "https://github.com/mutaician/genui-playground" },
	{ teamName: "Honey Paptan", projectTitle: "Veronica", githubLink: "https://github.com/HoneyPaptan/veronica" },
	{ teamName: "Sayan Ganguly", projectTitle: "Dendro-Meet", githubLink: "https://github.com/bitWise72/dendro-meet-clean" },
	{ teamName: "EVS", projectTitle: "AI Cybersecurity Dashboard", githubLink: "https://github.com/vishnu-varthan1/tamboaiproject" },
	{ teamName: "SOLO", projectTitle: "AI Expense Tracker", githubLink: "https://github.com/Ankit-singh-dot/tambo-ai-IntentOS" },
	{ teamName: "Swetha Satheesh", projectTitle: "Overwhelm", githubLink: "https://github.com/Serenehue/overwhelm" },
	{ teamName: "TASNEEM BANU", projectTitle: "MorphOS", githubLink: "https://github.com/tasneem38/MorphOS" },
	{ teamName: "SOLO", projectTitle: "College Copilot", githubLink: "https://github.com/alizahh-7/college-copilot" },
	{ teamName: "BitLinguals", projectTitle: "Ambria", githubLink: "https://github.com/mioNacs/Ambria" },
	{ teamName: "Myadam Sindhuja", projectTitle: "SpecAlign Logic Auditor", githubLink: "https://github.com/Sindhuja16-coder/specalign" },
	{ teamName: "Aditya Kumar Puri", projectTitle: "JackedAI", githubLink: "https://github.com/puri-adityakumar/jackedAI" },
	{ teamName: "Shiva", projectTitle: "AI Interior Designer", githubLink: "https://github.com/shivakumar2006/ai-interior-design" },
	{ teamName: "Sachin Singh", projectTitle: "Tambo Mission Control", githubLink: "https://github.com/Sachinsingh2002/tambo-mission-control" },
	{ teamName: "Nrusingh prasad swain", projectTitle: "tambo-wemakedevs-project", githubLink: "https://github.com/nrusingh-07/tambo-wemakedevs-project" },
	{ teamName: "SOLO", projectTitle: "DevOracle", githubLink: "https://github.com/Rakesh-18112006/devoracle" },
	{ teamName: "Affan khan", projectTitle: "AI Study Helper", githubLink: "https://github.com/affankhan-try/-tambo" },
	{ teamName: "Parthiv Makwana", projectTitle: "DO.T", githubLink: "https://github.com/parthiv11/do.t" },
	{ teamName: "Noslackers", projectTitle: "Sentinel", githubLink: "https://github.com/BakaAayush/tambo-sentinel" },
	{ teamName: "Lalit Borase", projectTitle: "Productivity Brain", githubLink: "https://github.com/lalitborase001/productivity-brain" },
	{ teamName: "SOLO", projectTitle: "TEGO", githubLink: "https://github.com/madhurimaa-9/tego" },
	{ teamName: "Adarsha.E", projectTitle: "DevEdu AI", githubLink: "https://github.com/Adarsh-031/DevEduAI" },
	{ teamName: "AATHAVAJAYANTH A S", projectTitle: "AJ AI Resume Builder", githubLink: "https://github.com/Aathava-Jayanth/AJ-AI-Resume-Builder" },
	{ teamName: "N A Krithika", projectTitle: "Unsaid", githubLink: "https://github.com/Krithika-NA/unsaid" },
	{ teamName: "Lokesh Sonawane", projectTitle: "DataMind", githubLink: "https://github.com/lokeshsw2/DataMind" },
	{ teamName: "Tofunmi", projectTitle: "Init UI", githubLink: "https://github.com/devtofunmi/init-ui" },
	{ teamName: "Sumanasri Paila", projectTitle: "ClearPlate", githubLink: "https://github.com/Sumanareddy13/clearplate-tambo-ui" },
	{ teamName: "SOLO", projectTitle: "AI Deployment Copilot", githubLink: "https://github.com/DevTwinkal/AI_Deployement_Assistant" },
	{ teamName: "SOLO", projectTitle: "Health Monitor", githubLink: "https://github.com/ManjuVasanth/tambo" },
	{ teamName: "Anuj Chauhan", projectTitle: "Student Companion", githubLink: "https://github.com/anujchauhann09/student-companion" },
	{ teamName: "Sanjay Balam", projectTitle: "MindFlow", githubLink: "https://github.com/Sanjay-Balam/mindflow-wemakedevs" },
	{ teamName: "KESAVARAJA M", projectTitle: "The Playbook", githubLink: "https://github.com/Kesavaraja67/the-playbook" },
	{ teamName: "Ravi Sahu", projectTitle: "Invisible UI", githubLink: "https://github.com/RaviSahu1520/invisible-ui-tambo" },
	{ teamName: "Pratham Chauhan", projectTitle: "Contract Guard", githubLink: "https://github.com/Pratham271/contract-guard" },
	{ teamName: "SOLO", projectTitle: "Fabric Decision Assistant", githubLink: "https://github.com/TJothiprakash/tambo-genui" },
	{ teamName: "kanugu rajesh", projectTitle: "FinGenie", githubLink: "https://github.com/kanugurajesh/Fingenie" },
	{ teamName: "SOLO", projectTitle: "SystemForge", githubLink: "https://github.com/AceAchyut/systemforge" },
	{ teamName: "SOLO", projectTitle: "Spring Festival", githubLink: "https://github.com/yuki-uix/spring-festival" },
	{ teamName: "Team Spark X", projectTitle: "ErrorIQ", githubLink: "https://github.com/Killer2OP/ErrorIQ" },
	{ teamName: "SOLO", projectTitle: "Tambo GitHub Explorer", githubLink: "https://github.com/Anuragsharma15-dell/git-explorer" },
	{ teamName: "Dhruva Wani", projectTitle: "AI Personal Finance Tracker", githubLink: "https://github.com/dhruvawani17/tambo" },
	{ teamName: "k2-team", projectTitle: "K2 Network", githubLink: "https://github.com/k2-network/k2-team-hackathon-tambo-ai" },
	{ teamName: "Kundan Suthar", projectTitle: "GetHired AI", githubLink: "https://github.com/kundan-suthar/gethired_ai" },
	{ teamName: "SOLO", projectTitle: "Maestro AI", githubLink: "https://github.com/waweruedwin8/maestro-ai" },
	{ teamName: "SK Faizanuddin", projectTitle: "Pathweaver AI", githubLink: "https://github.com/SKfaizan-786/pathweaver-ai" },
	{ teamName: "A.E.G.I.SxT.E.C.H", projectTitle: "Quiz Master", githubLink: "https://github.com/RCcoders/QUIZ-" },
	{ teamName: "SOLO", projectTitle: "Code Critic", githubLink: "https://github.com/tosif121/code-critic" },
	{ teamName: "Puja Moulik", projectTitle: "Generative UI Glide App", githubLink: "https://github.com/pujamoulik19-maker/generative-ui-glide-app" },
	{ teamName: "Arjun Mukesh", projectTitle: "Ally-Oop", githubLink: "https://github.com/arjunmukeshh/ally-oop" },
	{ teamName: "APIx Predators", projectTitle: "NeuroDesk", githubLink: "https://github.com/Adam-Jemmali/NeuroDesk" },
	{ teamName: "Priyansh Jain", projectTitle: "Subbo", githubLink: "https://github.com/Priyansh-Jain/Subbo" },
	{ teamName: "Jasmeen Sameer Shaikh", projectTitle: "Mom AI", githubLink: "https://github.com/jass2422/mom-ai-recipe-assistant" },
	{ teamName: "Verosity", projectTitle: "Foxie", githubLink: "https://github.com/AaKaShhhhhhhhh/Foxie" },
	{ teamName: "SOLO", projectTitle: "IndentOS", githubLink: "https://github.com/jjf2009/IntentOS" },
	{ teamName: "Sriram Kulkarni", projectTitle: "Jambo", githubLink: "https://github.com/BEASTSHRIRAM/Jambo" },
	{ teamName: "Chiranjeev Sahu", projectTitle: "Git-Scout", githubLink: "https://github.com/Chiranjeev-sahu/Git-Scout" },
	{ teamName: "SOLO", projectTitle: "AI Study Planner", githubLink: "https://github.com/Niranjan-1610/AI-Study-Planner" },
	{ teamName: "Rudra Pratap Singh", projectTitle: "Branion", githubLink: "https://github.com/Rudra-rps/Branion" },
	{ teamName: "Tech Trio", projectTitle: "AI Study UI", githubLink: "https://github.com/25it104-sreevarsha/WeMakeDevs-Hackathon" },
	{ teamName: "THE_NEVER_SELECTED", projectTitle: "Consensus.ai", githubLink: "https://github.com/Adidem23/Consensus.ai" },
	{ teamName: "Muhammad Talha", projectTitle: "Tambo Patient Care Coordinator", githubLink: "https://github.com/tal123ph/tambo-patient-coordinator" },
	{ teamName: "Sundaram Kumar Jha", projectTitle: "TechStore", githubLink: "https://github.com/sundaram2021/techstore" },
	{ teamName: "Solo", projectTitle: "ClinicalFlow", githubLink: "https://github.com/hsd2514/clinical-flow" },
	{ teamName: "Adnan khan", projectTitle: "Ops Assistant", githubLink: "https://github.com/addico786/ops-assistant" },
	{ teamName: "Team aayuti", projectTitle: "Moodify", githubLink: "https://github.com/Mehsbed/mood-dashboard" },
	{ teamName: "SOLO", projectTitle: "AdaptIQ", githubLink: "https://github.com/bishalbera/adaptiq" },
	{ teamName: "Kshitij", projectTitle: "DevDebug AI", githubLink: "https://github.com/kshitij1439/hacktambo" },
	{ teamName: "SOLO", projectTitle: "WanderAI", githubLink: "https://github.com/Allen-Saji/wander-ai" },
	{ teamName: "Zunairah Maasfa Khan", projectTitle: "IntentFlow", githubLink: "https://github.com/Zunairah-k/IntentFlow" },
	{ teamName: "The Feb Four", projectTitle: "Sehat Sathi", githubLink: "https://github.com/akshayahuja230/sehat-sathi" },
	{ teamName: "Srinivas", projectTitle: "WalletWake", githubLink: "https://github.com/sivaratrisrinivas/walletwake" },
	{ teamName: "Penna", projectTitle: "J.A.C.C.", githubLink: "https://github.com/Shyamyemuka/JACC" },
	{ teamName: "Team beginners", projectTitle: "Tambo Dashboard Generator", githubLink: "https://github.com/AmanDev200-cyber/Tambo-AI---Dashboard-Generator" },
	{ teamName: "Aman", projectTitle: "DevOS", githubLink: "https://github.com/07amansaini8684/DevOS" },
	{ teamName: "Team BuildOps", projectTitle: "AI Productivity Dashboard", githubLink: "https://github.com/unknowdeepanshu/AI-Productivity-Dashboard" },
	{ teamName: "Team Baked", projectTitle: "Capsule", githubLink: "https://github.com/Ashrith-Yathin/Capsule-DevOps" },
	{ teamName: "Suhel Ali", projectTitle: "Institute Website", githubLink: "https://github.com/suhel6388/institute_website" },
	{ teamName: "SOLO", projectTitle: "AI Roadmap generator", githubLink: "https://github.com/kashish00208/UI_Strike" },
	{ teamName: "4Bytes", projectTitle: "atomic-UI", githubLink: "https://github.com/kekubhai/atomicdocs-UI" },
	{ teamName: "Prajwal R", projectTitle: "Blueprint", githubLink: "https://github.com/niranjankumar7/interview-tracker" },
	{ teamName: "Solo", projectTitle: "AI Operations Manager", githubLink: "https://github.com/AnkitAnandMastery17/AI-Operations-Manager" },
	{ teamName: "VIVEKANANTHAN S", projectTitle: "CareerForce", githubLink: "https://github.com/svivek19/AI-Career-Copilot-With-Tambo-AI" },
	{ teamName: "YASH BANSAL", projectTitle: "RealityForger", githubLink: "https://github.com/demonstrikkk/jedi-warr" },
	{ teamName: "Triple A", projectTitle: "RepoExplainer", githubLink: "https://github.com/rahim709/RepoExplainer" },
	{ teamName: "Dikshant Jha", projectTitle: "CloudAtlas", githubLink: "https://github.com/dikshant182004/cloudatlas" },
	{ teamName: "ORIGIN", projectTitle: "Holocron Nexus", githubLink: "https://github.com/JATIN-1607/HolocronNexus" },
	{ teamName: "Shlok Ranjan", projectTitle: "GitStory", githubLink: "https://github.com/Random-Pikachu/GitStory" },
	{ teamName: "Inteli Devs", projectTitle: "Obsidian vault manager", githubLink: "https://github.com/C-Icaro/tamboHack" },
	{ teamName: "Priyanka", projectTitle: "InsightOS", githubLink: "https://github.com/priyankashah3107/tambo-hackathon" },
	{ teamName: "SOLO", projectTitle: "Deep Research Agent", githubLink: "https://github.com/addy1947/deepreserchAgent" },
	{ teamName: "SOLO", projectTitle: "Tambo CRM", githubLink: "https://github.com/Farhantigadi/tambo-db" },
	{ teamName: "SpiderMonkeys", projectTitle: "GitHub Deck", githubLink: "https://github.com/Paul-Annay/github-deck" },
	{ teamName: "Kaushal Yadav", projectTitle: "AI Dashboard Assistant", githubLink: "https://github.com/Kaushalendra-Marcus/AI-Dashboard-Assistant" },
	{ teamName: "Nancy Sangani", projectTitle: "TicketMaster AI", githubLink: "https://github.com/nancysangani/ticketmaster-ai" },
	{ teamName: "Shrikant Kole", projectTitle: "Axent AI", githubLink: "https://github.com/shrikantkole1/axent-ai" },
	{ teamName: "PaperPrep", projectTitle: "PaperPrep", githubLink: "https://github.com/aashishpanthi/paperprep-tambo" },
	{ teamName: "Last Commit", projectTitle: "ThinkFlow AI", githubLink: "https://github.com/m-karthika14/thinkflow-AI-tambo" },
	{ teamName: "Promptoria", projectTitle: "Opsuna", githubLink: "https://github.com/Pulkit7070/Opsuna" },
	{ teamName: "Avinash Rawat", projectTitle: "ContextFlow", githubLink: "https://github.com/onlyAvinash/contextFlow" },
	{ teamName: "PeakPanthers", projectTitle: "HealthScribe", githubLink: "https://github.com/Amxnnn/HealthScribe" },
	{ teamName: "Squad", projectTitle: "TalkToGitHub", githubLink: "https://github.com/sumaiya-13/TalkToGithub" },
	{ teamName: "Devnity", projectTitle: "Debuggo", githubLink: "https://github.com/KatapallyVivek/debuggo" },
	{ teamName: "shinchanClan", projectTitle: "Webify", githubLink: "https://github.com/sarthaksarthak9/Webify" },
	{ teamName: "Shikhar Verma", projectTitle: "Stratify", githubLink: "https://github.com/Shikhyy/stratify" },
	{ teamName: "Soham Kharat", projectTitle: "GP F1", githubLink: "https://github.com/Sohamkhrt/GP" },
	{ teamName: "Anurag Thakur", projectTitle: "Landing Page Generator", githubLink: "https://github.com/DevAnuragT/conversational_product_designer" },
	{ teamName: "SOLO", projectTitle: "SymptomSync AI", githubLink: "https://github.com/Atharva-026/SymptomSync-Ai" },
	{ teamName: "Alpha coders", projectTitle: "FreshSaver", githubLink: "https://github.com/Utpal-Kalita/FreshSaver" },
	{ teamName: "Arceus", projectTitle: "ditto", githubLink: "https://github.com/bharathkumaarr/ditto" },
	{ teamName: "HACK TO THE FUTURE", projectTitle: "Galactic Planner", githubLink: "https://github.com/ABHISHEK-PRASAD-BAHELIYA/Galactic-planner" },
	{ teamName: "Brain Byte X", projectTitle: "VentureLens AI", githubLink: "https://github.com/Kumaaragurubaran-del/venturelensai" },
	{ teamName: "TeamX", projectTitle: "Tambo Lens", githubLink: "https://github.com/siddismyusername/tambo-lens" },
	{ teamName: "Vyse", projectTitle: "LogPose", githubLink: "https://github.com/Itz-Agasta/LogPose" },
	{ teamName: "SOLO", projectTitle: "RepoChat", githubLink: "https://github.com/aryan877/repochat" },
	{ teamName: "OMESH KUMAR", projectTitle: "Zero-UI Admin", githubLink: "https://github.com/Rhae-Shane/Zero-UI-" },
	{ teamName: "Karan Singh Bisht", projectTitle: "GlassBox", githubLink: "https://github.com/KaranSinghBisht/glassbox" },
	{ teamName: "JANESH KAPOOR", projectTitle: "LickUI", githubLink: "https://github.com/JaneshKapoor/lickui" },
	{ teamName: "CodeBrewers", projectTitle: "TAMBO SKY", githubLink: "https://github.com/GowthamAvula/uistrike" },
	{ teamName: "Ayan Masood", projectTitle: "UI-Smith", githubLink: "https://github.com/Ayan-M-Dev/UI-Smith" },
	{ teamName: "AXIOMS", projectTitle: "Travel Genie", githubLink: "https://github.com/nisarga-am/travel-genie" },
	{ teamName: "Ashita", projectTitle: "Tambo Generative UI Playground", githubLink: "https://github.com/devandop/tambo-playground" },
	{ teamName: "Mog Squad", projectTitle: "Derived", githubLink: "https://github.com/Sri-Krishna-V/Derived-WMD" },
	{ teamName: "SOLO", projectTitle: "Sacsa-Sentinel", githubLink: "https://github.com/Tusharkshahi/sacsa-sentinel" },
	{ teamName: "Everything Everywhere All At Once", projectTitle: "Flogen", githubLink: "https://github.com/asHawcker/flogen" },
	{ teamName: "NotLuckyPatchers", projectTitle: "Travel co-pilot", githubLink: "https://github.com/sankalp771/tambo_mmt" },
	{ teamName: "Shantanu Gahtori", projectTitle: "PRDly", githubLink: "https://github.com/Shantanu993/PRDly" },
	{ teamName: "Mohit Thapa", projectTitle: "MeetingMind", githubLink: "https://github.com/M0hitThapa/MeetingMind" },
	{ teamName: "Ankit Sharma", projectTitle: "Creative Content", githubLink: "https://github.com/akcode7/tambo-hackathon" },
	{ teamName: "Rakesh Mahendran", projectTitle: "Flakers Studio", githubLink: "https://github.com/RakeshMahendran/Flakers-studio" },
	{ teamName: "3 musketeers", projectTitle: "CodeLore", githubLink: "https://github.com/VanshNagpal10/Codelore" },
	{ teamName: "Afsar I", projectTitle: "The UI Talks Back", githubLink: "https://github.com/afsarinayathkhan2004/ui-talks-back" },
	{ teamName: "Shivaaganesh", projectTitle: "Tambo Compliance Dashboard", githubLink: "https://github.com/shivaaganesh3/Tambo-hackathon" },
	{ teamName: "Rishi Jat", projectTitle: "Intent Admin Console", githubLink: "https://github.com/rishi-jat/intent-admin-console" },
	{ teamName: "Indira Coders", projectTitle: "Emotion-Aware Journaling", githubLink: "https://github.com/Ankush82/IndiraCoders" },
	{ teamName: "Redemption", projectTitle: "StudyGenie", githubLink: "https://github.com/Lingaraj-Patil/tambo-hackathon" },
	{ teamName: "Mano Janani R", projectTitle: "ReadOrigin", githubLink: "https://github.com/ManoJananiR/Hackathon" },
	{ teamName: "Domendra", projectTitle: "AccessForge", githubLink: "https://github.com/azadDsync/access-forge" },
	{ teamName: "Gradus", projectTitle: "AI Interview Platform", githubLink: "https://github.com/HiAmanAgrawal/Interview-AI" },
	{ teamName: "solo", projectTitle: "Budget AI", githubLink: "https://github.com/tejas-2232/budget-ai" },
	{ teamName: "Tambo Pulse", projectTitle: "Tambo Pulse", githubLink: "https://github.com/nilam576/tambo_pulse" },
	{ teamName: "The Jugglers", projectTitle: "CanLearn", githubLink: "https://github.com/kalashjain23/CanLearn" },
	{ teamName: "The tilines", projectTitle: "Flow State", githubLink: "https://github.com/david-mamani/flow-state-hackathon" },
	{ teamName: "SOLO", projectTitle: "Cosmos", githubLink: "https://github.com/nags0x/cosmos" },
	{ teamName: "Aniket Das", projectTitle: "AI Campus Assistant", githubLink: "https://github.com/Aniket102005/ai-campus-assistant" },
	{ teamName: "SOLO", projectTitle: "Intent-Driven Invisible UI", githubLink: "https://github.com/vismaya079/intent-driven-ui" },
	{ teamName: "Kshitij Bhardwaj", projectTitle: "Tambo Studio", githubLink: "https://github.com/KshitijBhardwaj18/tambostudio" },
	{ teamName: "Titans", projectTitle: "AI Voice Assistant", githubLink: "https://github.com/8523Hema/AI-powered-voice-assistant" },
	{ teamName: "Shreya Pandey", projectTitle: "Git Visually", githubLink: "https://github.com/shreyap2702/git-visually" },
	{ teamName: "Alok Dangre", projectTitle: "SRE Command Center", githubLink: "https://github.com/alokdangre/SRE-Command-Center" },
	{ teamName: "Salmaan M", projectTitle: "SmartTrip", githubLink: "https://github.com/Salmaan-M/SmartTrip-AI_Travel_Planner" },
	{ teamName: "shubham kumar", projectTitle: "Cortex", githubLink: "https://github.com/shubham-01-star/Cortex" },
	{ teamName: "SOLO", projectTitle: "Insyte", githubLink: "https://github.com/oscarosk/Insyte" },
	{ teamName: "SOLO", projectTitle: "Secure AI", githubLink: "https://github.com/debaa98/secure-AI" },
	{ teamName: "Tech Titan", projectTitle: "ForceUI", githubLink: "https://github.com/ishwa07/ForceUI-Project" },
	{ teamName: "Sudeep Khandekar", projectTitle: "Planning Assistant", githubLink: "https://github.com/sudeepkhandekar99/tambo-wemakedev" },
	{ teamName: "Omkar Gujja", projectTitle: "ProShop", githubLink: "https://github.com/omkarg01/Proshop" },
	{ teamName: "Manjunath Patil", projectTitle: "Kyber", githubLink: "https://github.com/manjunath5513/Kyber" },
	{ teamName: "neeraj", projectTitle: "TripWiz", githubLink: "https://github.com/Neeraj-gagat/TripWiz" },
	{ teamName: "SOLO", projectTitle: "DevBoard", githubLink: "https://github.com/aadarshx22/devboard" },
	{ teamName: "Ariya P", projectTitle: "AutoPilot Agent", githubLink: "https://github.com/Ariya-rithvik/TaskPilot" },
	{ teamName: "Lowkirkiuene", projectTitle: "Crypto Hunter", githubLink: "https://github.com/pranavdevv/crypto_hunto" },
	{ teamName: "Fudail Mohammed Zafar", projectTitle: "TamboEarth", githubLink: "https://github.com/fudailzafar/tambo-earth" },
	{ teamName: "Karan", projectTitle: "ForgeAI", githubLink: "https://github.com/karan0207/forge-ai" },
	{ teamName: "SOLO", projectTitle: "Torq", githubLink: "https://github.com/bikash1376/torq" },
	{ teamName: "Vidhi Singh", projectTitle: "Tambo Platform", githubLink: "https://github.com/vidhisingh14/tambo_wemakedev" },
	{ teamName: "Milan Patel", projectTitle: "Tambo ExpenseGraphica", githubLink: "https://github.com/MilanPatel28/Tambo_ExpenseGraphica" },
	{ teamName: "SOLO", projectTitle: "TamboBase", githubLink: "https://github.com/varshithm7x/tambo-supabase-viz" },
	{ teamName: "Byte-Me", projectTitle: "StudBud", githubLink: "https://github.com/Rudresh-0709/TamboHackathon" },
	{ teamName: "ChimpMonk", projectTitle: "Schema Driven UI", githubLink: "https://github.com/MaringantiYashwanth/SchemaDrivenAiForAiGeneratedInterfaces" },
	{ teamName: "Apoorv Gupta", projectTitle: "Job Search Copilot", githubLink: "https://github.com/StephCurry07/job-search-copilot" },
	{ teamName: "Sujit Kumar Sarkar", projectTitle: "FixFlow", githubLink: "https://github.com/sujitKrS04/FixFlow" },
	{ teamName: "Praveen v", projectTitle: "Podcast Video App", githubLink: "https://github.com/PraveenVenkatachlam/podcast-frontend" },
	{ teamName: "SOLO", projectTitle: "PMcrush", githubLink: "https://github.com/amanc1248/cursor-for-pm" },
	{ teamName: "Syed Arman Ali", projectTitle: "Dashboard Builder", githubLink: "https://github.com/SyedArmanAli2003/tambo-hackathon-app" },
	{ teamName: "Saurabh Joshi", projectTitle: "Nexus", githubLink: "https://github.com/FullStackSorcerer/Nexus-Generative-Flow" },
	{ teamName: "Deepanshu Yadav", projectTitle: "Nebula Sentinel", githubLink: "https://github.com/Dydipanshu/ui-whisperer" },
	{ teamName: "Tambo OS", projectTitle: "Tambo OS", githubLink: "https://github.com/tambo-os/tambo-os" },
	{ teamName: "solo", projectTitle: "Virus Team Login Page", githubLink: "https://github.com/virus-c-x/tambo-login-page-template-" },
	{ teamName: "SOLO", projectTitle: "Lets Chat with Tambo", githubLink: "https://github.com/vivek-kumar-P/lets_chat_with_tambo" },
	{ teamName: "Raj Trikha", projectTitle: "Orbital Command Nexus", githubLink: "https://github.com/RajTrikha/Orbital-Command-Nexus" },
	{ teamName: "BitWrappers", projectTitle: "CanvasX", githubLink: "https://github.com/AbbasReads/CanvasX" },
	{ teamName: "Honey Badger", projectTitle: "AnalyseAnyRepo", githubLink: "https://github.com/YuvrajSHAD/AnalyseAnyRepo" },
	{ teamName: "RISHITA SEAL", projectTitle: "VidhiFlow", githubLink: "https://github.com/Pixie-19/VidhiFlow" },
	{ teamName: "IGRIS", projectTitle: "Sentinel AI", githubLink: "https://github.com/vishalkumargeed/Tambo-IGRIS" },
	{ teamName: "MD Aaftab Alam", projectTitle: "Intelligent CRM", githubLink: "https://github.com/iamMD01/intelligent_CRM" },
	{ teamName: "Ananya", projectTitle: "SafeContract", githubLink: "https://github.com/soulno-22/SafeContract" },
	{ teamName: "Rohit Thorat", projectTitle: "Tambo AI Analytics Dashboard", githubLink: "https://github.com/roht2103/tambo-ai-analytics-dashboard" },
	{ teamName: "Lakshmi V", projectTitle: "Disaster Hub", githubLink: "https://github.com/lakshmiv3322/disaster-hub-ai" },
	{ teamName: "SOLO", projectTitle: "Analytics Tool", githubLink: "https://github.com/DivyanshTiwari20/my-tambo-app" },
	{ teamName: "solo", projectTitle: "EcoTrack", githubLink: "https://github.com/SakthiV4/Green-Habit-Tracker" },
	{ teamName: "Pheonix", projectTitle: "Cyber-bullying reporting", githubLink: "https://github.com/anitha646/Cyber-bullying-reporting-system" },
	{ teamName: "Sonu Suresh", projectTitle: "TaskStack", githubLink: "https://github.com/tambo-h/crowdlens" },
	{ teamName: "Aryavart", projectTitle: "Nexus Health Gateway", githubLink: "https://github.com/RudyMontoo/AIHelthcare" },
	{ teamName: "SOLO", projectTitle: "Arin", githubLink: "https://github.com/Shivam-Katare/arin" },
	{ teamName: "Allbots", projectTitle: "EarthLink AI", githubLink: "https://github.com/Azaan816/EarthLink-AI" },
	{ teamName: "Pravin Wavare", projectTitle: "IntentUI", githubLink: "https://github.com/yash9154/IntentUI" },
	{ teamName: "solo", projectTitle: "CrisisCompass", githubLink: "https://github.com/Satianurag/crisis_compass" },
	{ teamName: "Turiya", projectTitle: "SkyObserv", githubLink: "https://github.com/ankitchouhan119/SkyObserv" },
	{ teamName: "Trupti Ganeshkar", projectTitle: "Honey-flower school", githubLink: "https://github.com/Tru06/Honey-flower-school" },
	{ teamName: "Suman Giri", projectTitle: "Edify", githubLink: "https://github.com/shumhn/Edify" },
	{ teamName: "Prasenjeet Kumar", projectTitle: "TrendPulse", githubLink: "https://github.com/Prasen2/TrendPulse" },
	{ teamName: "Sagnik Ghosh", projectTitle: "TamboFlow", githubLink: "https://github.com/sagnik26/Tambo-Canvas" },
	{ teamName: "Sumit Chawla", projectTitle: "TIL Log", githubLink: "https://github.com/SamChawla/til-log" },
	{ teamName: "Arjun Sharma", projectTitle: "ASCEND", githubLink: "https://github.com/Spidy29/ascend-tambo-ai-hackathon" },
	{ teamName: "SOLO", projectTitle: "Shoestore", githubLink: "https://github.com/PZ2810/Shoestore" },
	{ teamName: "Void", projectTitle: "GitStory", githubLink: "https://github.com/Random-Pikachu/GitStory" },
	{ teamName: "Raj Gupta", projectTitle: "Tutor Dashboard", githubLink: "https://github.com/Raj-G07/tambo-tutor-dashboard" },
	{ teamName: "Akash Mohan", projectTitle: "Kyber", githubLink: "https://github.com/Akash-How/Kyber-ai" },
	{ teamName: "wowTambo", projectTitle: "Medileon", githubLink: "https://github.com/saurabhduhariya/Medileon" },
	{ teamName: "Almighty", projectTitle: "ArguUI", githubLink: "https://github.com/Pritam-Sing-2025/arguui" },
	{ teamName: "Yashas M N", projectTitle: "DashHub", githubLink: "https://github.com/noobie-bob/DashHub" },
	{ teamName: "SOLO", projectTitle: "Canvas AI", githubLink: "https://github.com/Prakhar2025/canvas.ai" },
	{ teamName: "TechTonics", projectTitle: "StudentIQ Agent", githubLink: "https://github.com/vaishnavi-parodkar/studentiqAgent" },
	{ teamName: "Paras Jagdale", projectTitle: "AI Life Dashboard", githubLink: "https://github.com/ParasJagdale/Tambo-Generative-Dashboard" },
	{ teamName: "SOLO", projectTitle: "AI Crypto Analysis UI", githubLink: "https://github.com/ajaygoud116/AI-driven-crypto-analysis-UI-using-Tambo" },
	{ teamName: "Simranjeet Singh", projectTitle: "Auri", githubLink: "https://github.com/esemsc-ss2524/auri" },
	{ teamName: "Shubham Kondekar", projectTitle: "Todo Application", githubLink: "https://github.com/kondekarshubham123/UI-Strikes-Hackathon-Todo-Application" },
	{ teamName: "Vanguard", projectTitle: "Vangraph", githubLink: "https://github.com/hebypaul/Vangraph" },
	{ teamName: "Unique", projectTitle: "CRI Command Center", githubLink: "https://github.com/SaiAkash0/Tambo_Hackathon" },
	{ teamName: "Anuhya kotapati", projectTitle: "Tambo Shopping", githubLink: "https://github.com/anuhya-kotapati/Tambo_Shopping" },
	{ teamName: "GenOrchestra", projectTitle: "ShopSage", githubLink: "https://github.com/piyushagarwal-55/hackathon-we-make-devs" },
	{ teamName: "EdgeCase", projectTitle: "Endpoint Architect", githubLink: "https://github.com/DakshD10/Endpoint-Architect" },
	{ teamName: "Tharunya Pathipati", projectTitle: "JobOS", githubLink: "https://github.com/Tharunya07/JobOS" },
	{ teamName: "Sudarshan", projectTitle: "ResQ-AI", githubLink: "https://github.com/11Sudarshan/Resq-AI" },
	{ teamName: "Anish Maheshwari", projectTitle: "OpsPilot", githubLink: "https://github.com/anish-maheshwari/OpsPilot" },
	{ teamName: "Rahul pandey", projectTitle: "SafeOps Co-pilot", githubLink: "https://github.com/CoderRahul01/safeops-copilot" },
	{ teamName: "SOLO", projectTitle: "Smart Project Autopilot", githubLink: "https://github.com/thekishandev/smart-project-autopilot" },
	{ teamName: "Samarth Saxena", projectTitle: "Deep Dungeon", githubLink: "https://github.com/samarthsaxena2004/playdungeon" },
	{ teamName: "Hasktastic Nomads", projectTitle: "TraceLens AI", githubLink: "https://github.com/AP952005/tracelens-ai" },
	{ teamName: "Athidathan K", projectTitle: "DeepDive", githubLink: "https://github.com/Savvy7/whiteBox_kimi" },
	{ teamName: "TEAM SMVIT", projectTitle: "Agentic Product Composer", githubLink: "https://github.com/SairajMN/Tambo-AI" },
	{ teamName: "NeuroNova", projectTitle: "Hackathon Copilot", githubLink: "https://github.com/Shravanii-patil/Hackathon-copilot" },
	{ teamName: "Naomi Pereira", projectTitle: "SimOS", githubLink: "https://github.com/NaomiiAP/SimOS" },
	{ teamName: "Kaushalendra Singh", projectTitle: "AI Business Intelligence", githubLink: "https://github.com/Kaushalendra-Marcus/AI-Business-Intelligence" },
	{ teamName: "CodeRed", projectTitle: "Civic AI", githubLink: "https://github.com/MATRIX-ux-arch/civic_ai" },
	{ teamName: "Ashish Guleria", projectTitle: "WealthSense AI", githubLink: "https://github.com/ashishguleria04/WealthSense-AI" },
	{ teamName: "Olibhia Ghosh", projectTitle: "Invoice Manager", githubLink: "https://github.com/OlibhiaGhosh/Invoice_manager" },
	{ teamName: "Raj shakya", projectTitle: "ASK DB", githubLink: "https://github.com/Rjshakya/spl-agent" },
];

export { winningProjects, topProjects, otherProjects };
