const winningProjects = [
	{
		teamName: "Rakshak",
		projectTitle: "ETMS — AI-Powered Safety Infrastructure",
		description:
			"A distributed, privacy-first, edge-based system that combines vision intelligence, behavioral anomaly detection, physiological monitoring, indoor tracking, and deterministic emergency orchestration. It detects falls, wandering, health anomalies, and unsafe situations in real time — then applies strict policy-driven escalation, including voice confirmation and structured emergency reporting.",
		githubLink: "https://github.com/Pavankumar07s/Vision-Possible.git",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/Lqu81ANxR8I",
		prize: "1st Place",
	},
	{
		teamName: "Karthika M",
		projectTitle: "OceanWatch — Real-Time Marine Intelligence",
		description:
			"A real-time environmental intelligence agent powered by Vision Agents that watches and listens to marine environments as they evolve. Using Vision Agents for live video and audio streaming, OceanWatch detects environmental pressure and translates live signals into actionable insights — helping identify risks before irreversible harm occurs.",
		githubLink: "https://github.com/m-karthika14/Oceanwatch-ai",
		deployedLink: "https://oceanwatch-ai.vercel.app",
		youtubeEmbed: "https://www.youtube.com/embed/KR1CTbZLak4",
		prize: "2nd Place",
	},
	{
		teamName: "Marvellous",
		projectTitle: "Watcher — Real-Time Posture Corrector",
		description:
			"A watchmate that sits around non-invasively to help correct posture defects while working. Uses a custom processor to mathematically derive angles from YOLO model results for posture analysis and feeds it to the agent that assigns a posture score and provides real-time feedback.",
		githubLink: "https://github.com/0x-aut/watcherserver",
		deployedLink: "https://watcherweb.vercel.app/",
		youtubeEmbed: "https://www.loom.com/embed/cee28fb93a2d4cfe8346723af5e753b6",
		prize: "3rd Place",
	},
];

const topProjects: { teamName: string; projectTitle: string; description: string; githubLink: string; deployedLink: string; youtubeEmbed: string }[] = [];

const otherProjects: { teamName: string; projectTitle: string; githubLink: string }[] = [
	{ teamName: "Nestor Campos", projectTitle: "FitBuddy", githubLink: "https://github.com/nescampos/fitbuddy" },
	{ teamName: "Bedanta Chatterjee", projectTitle: "Vision Agent", githubLink: "https://github.com/rupac4530-creator/vision-agent" },
	{ teamName: "Jaya Dubey", projectTitle: "Cricket DRS AI", githubLink: "https://github.com/jaya6400/Vision-Agents/tree/main/examples/09_cricket_umpire" },
	{ teamName: "Spandan Mukherjee", projectTitle: "Local-First AI Astrologer", githubLink: "https://github.com/SpandanM110/Local-First-AI-Astrologer" },
	{ teamName: "Cian", projectTitle: "ArduinoVision", githubLink: "https://github.com/mutaician/arduino-vision" },
	{ teamName: "Emmanuel Olorunleke", projectTitle: "RevVision", githubLink: "https://github.com/EmmyMay/RevVision" },
	{ teamName: "Kapil Shastri", projectTitle: "SentinelAI", githubLink: "https://github.com/kapilshastriwork-maker/sentinelai.git" },
	{ teamName: "Sree Varsha M", projectTitle: "VisionCoach", githubLink: "https://github.com/25it104-sreevarsha/visioncoach" },
	{ teamName: "Shivansh Bagga", projectTitle: "LiveSense", githubLink: "https://github.com/baggashivansh/LiveSense.git" },
	{ teamName: "Rohan Jain", projectTitle: "GuardianLens", githubLink: "https://github.com/rohanjain1648/GuardianLens" },
	{ teamName: "Samarth Shendre", projectTitle: "SentinelMind", githubLink: "https://github.com/i-m-samarth-cs/sentinelmind.git" },
	{ teamName: "Dhruva Wani", projectTitle: "AI Medical Wellness Assistant", githubLink: "https://github.com/dhruvawani17/video-ai" },
	{ teamName: "Sonu Suresh", projectTitle: "RoastMyRoom.ai", githubLink: "https://github.com/sonu-suresh/RoastMyRoom.ai" },
	{ teamName: "Akintayo Ajibola", projectTitle: "LiveScene AI", githubLink: "https://github.com/Jaybea00/LiveScene-AI.git" },
	{ teamName: "Akash Mohan", projectTitle: "Vision Agent Monitor", githubLink: "https://github.com/Akash-How/Vision_Agent" },
	{ teamName: "Rishika Aggarwal", projectTitle: "Sentinel KYC", githubLink: "https://github.com/rishika-on-git/sentinel-kyc" },
	{ teamName: "Abdulqadir Jimoh", projectTitle: "Trada", githubLink: "https://github.com/Abdul-Jimoh/Trada" },
	{ teamName: "Arunkumar", projectTitle: "InterviewCoach", githubLink: "https://github.com/arunsadhasivam/AIRepositories/tree/master/Projects/VISON_AGENTS/InterviewCoach" },
	{ teamName: "Gautam Khosla", projectTitle: "MetaShift", githubLink: "https://github.com/GautamTalksDev/MetaShift" },
	{ teamName: "Makiko Ohashi", projectTitle: "Pencil Stuck Marker", githubLink: "https://github.com/MakikoOhashi/pencil-stuck-marker" },
	{ teamName: "Anurag Sharma", projectTitle: "Building with Vision Agent", githubLink: "https://github.com/Anuragsharma15-dell/Building-with-vision-agent" },
	{ teamName: "Rimi Chakraborty", projectTitle: "Repository Security Checker", githubLink: "https://github.com/rimichak/repository_security_checker" },
	{ teamName: "Muhammad Talha", projectTitle: "ReVision Studio", githubLink: "https://github.com/tal123ph/ReVision-Studio" },
	{ teamName: "Aniruddha Adak", projectTitle: "Vision Possible Blog", githubLink: "https://github.com/aniruddhaadak80" },
	{ teamName: "Tharunya", projectTitle: "Posture Coach", githubLink: "https://github.com/Tharunya07/posture-coach" },
	{ teamName: "Abhay Singh", projectTitle: "Visionary AI", githubLink: "https://github.com/abhay-codes07/visionary_ai" },
	{ teamName: "Swagatika Beura", projectTitle: "VisionMate AI", githubLink: "https://github.com/swagatika60/Vision-Agent" },
	{ teamName: "Abhay Gupta", projectTitle: "AccessSphere", githubLink: "https://github.com/abhayguptas/accesssphere.git" },
	{ teamName: "Mano Janani R", projectTitle: "AI Interview Simulator", githubLink: "https://github.com/ManoJananiR/Hackathon-vision-agent-" },
	{ teamName: "Hemanth C S", projectTitle: "CogniSync", githubLink: "https://github.com/hemanthcs34/visionagent" },
	{ teamName: "Akshit Agarwal", projectTitle: "VAWMS", githubLink: "https://github.com/akshitag001/VAWMS" },
	{ teamName: "Ibrahim Abdulmajeed", projectTitle: "AI Fitness Coach", githubLink: "https://github.com/Dcrony" },
	{ teamName: "Domendra", projectTitle: "Scout", githubLink: "https://github.com/azadDsync/scout" },
	{ teamName: "Will Wild", projectTitle: "Omni-Agent", githubLink: "https://github.com/wildhash/omni-agent" },
	{ teamName: "Mohit Jeswani", projectTitle: "AI Badminton Coach", githubLink: "https://github.com/mohitjeswani01/badminton-coach" },
	{ teamName: "Tosif", projectTitle: "FitAgent", githubLink: "https://github.com/tosif121/fitness-agent.git" },
	{ teamName: "Vishwa Kumaresh", projectTitle: "WorldLens", githubLink: "https://github.com/Vishwa-docs/WeMakeDevs-Vision-Possible-Hackathon" },
	{ teamName: "Tech Titans", projectTitle: "AgriScan AI", githubLink: "https://github.com/sabariganesan25/agri.git" },
	{ teamName: "Aniket Das", projectTitle: "CivicWatch", githubLink: "https://github.com/Aniket102005/CivicWatch" },
	{ teamName: "Balaji Thukuntala", projectTitle: "FootworkAI", githubLink: "https://github.com/BalajiReddy1/FootworkAI" },
	{ teamName: "Varun Gupta", projectTitle: "LightLens", githubLink: "https://github.com/Shadow-Flash/LightLens" },
	{ teamName: "Kaustubh Upadhyay", projectTitle: "SemSorter", githubLink: "https://github.com/KaustubhUp025/SemSorter" },
	{ teamName: "Pankaj Kumar Goyal", projectTitle: "CricketMind", githubLink: "https://github.com/pankaj10032/Multimodel-Cricket-Agent/" },
	{ teamName: "Uttam Kumar Singh", projectTitle: "PoseCoach AI", githubLink: "https://github.com/uttamkumarsingh642004/posecoach-ai" },
	{ teamName: "Kartik Pal", projectTitle: "AI Calisthenics Coach", githubLink: "https://github.com/palkartik07/calisthenics-coach" },
	{ teamName: "EdgeEye", projectTitle: "PlayByt", githubLink: "https://github.com/something1703/PlayByt" },
	{ teamName: "Abhishek Prasad Baheliya", projectTitle: "Vision Fraud Agent", githubLink: "https://github.com/ABHISHEK-PRASAD-BAHELIYA/vision-fraud-agent" },
	{ teamName: "Zohaib Malik", projectTitle: "Easy Learning", githubLink: "https://github.com/zohaibkhan745/Easy-Learning" },
	{ teamName: "Aryan Kumar", projectTitle: "CandidAI", githubLink: "https://github.com/aryan877/candidai" },
	{ teamName: "Arjun", projectTitle: "OneVision", githubLink: "https://github.com/Arjunhg/onevision" },
	{ teamName: "Harsh Saxena", projectTitle: "Agentic EyeCare Copilot", githubLink: "https://github.com/MonotonousHarsh/EyeCareBackend" },
	{ teamName: "Mehboob Alam", projectTitle: "Drishti AI", githubLink: "https://github.com/Mahboob-A/drishti-ai" },
	{ teamName: "M Yamini Priya", projectTitle: "Vision Agent Interview Coach", githubLink: "https://github.com/Yamini26284/Vision-Agent" },
	{ teamName: "Trupti Ganeshkar", projectTitle: "Vision Agent Protocol", githubLink: "https://github.com/Tru06/vision-agent" },
	{ teamName: "Jeevith G", projectTitle: "Cricket Batting Analyzer", githubLink: "https://github.com/jeevithg090/VideoAI" },
	{ teamName: "Jamal Akinola", projectTitle: "ARIA", githubLink: "https://github.com/jams24/aria-vision-agent" },
	{ teamName: "Ayomide Oladeji", projectTitle: "Sentinel AI Safety", githubLink: "https://github.com/realxpen/Sentinel_AI" },
	{ teamName: "Raj Gupta", projectTitle: "Visions Communication Coach", githubLink: "https://github.com/Raj-G07/Communication_expert" },
	{ teamName: "Sanskriti Singh", projectTitle: "Touchless Gesture Controller", githubLink: "https://github.com/its-sanskriti/touchless-gesture-controller.git" },
	{ teamName: "Ashutosh Kumar Tripathi", projectTitle: "Medication Proctor", githubLink: "https://github.com/AshutoshIIT1234/medication-proctor" },
	{ teamName: "Vicky Kumar", projectTitle: "Cognivise", githubLink: "https://github.com/algsoch/Cognivise.git" },
	{ teamName: "Gaurav Chauhan", projectTitle: "Vidur AI CCTV Fire Alarm", githubLink: "https://github.com/Gaurav0369/Vidur-AI-CCTV-Fire-Alarm" },
	{ teamName: "Chinwuba Israel", projectTitle: "VibeCheck", githubLink: "https://github.com/chiizzy1/vibecheck" },
	{ teamName: "Kshitij", projectTitle: "VisionStudio AI", githubLink: "https://github.com/kshitij1439/stream-it-ai-classified" },
	{ teamName: "Atharva Naik", projectTitle: "StyleSense AI", githubLink: "https://github.com/Atharva-026/classified" },
	{ teamName: "Kevin Pereira", projectTitle: "ShadowID", githubLink: "https://github.com/Xcalibur-hub/ShadowID/tree/main" },
	{ teamName: "Phoenix", projectTitle: "ISL Voice", githubLink: "https://github.com/princepal-dev/we-make-devs" },
	{ teamName: "Srija Akula", projectTitle: "Interview Pressure Analyzer", githubLink: "https://github.com/srija1102/Vision-Agents/tree/main/examples/09_interview_pressure_analyzer" },
	{ teamName: "Tushar Khatri", projectTitle: "BlindSight AI", githubLink: "https://github.com/tusharkhatriofficial/blindsight-ai" },
	{ teamName: "Abhishek H", projectTitle: "HeyYou", githubLink: "https://github.com/handshek/hey-you" },
	{ teamName: "Pritam Saha", projectTitle: "Sight-Notes", githubLink: "https://github.com/Saha-7/Sight-Notes" },
	{ teamName: "Twinkal Sahu", projectTitle: "InterviewOS", githubLink: "https://github.com/DevTwinkal/InterviewOS" },
	{ teamName: "Shantanu", projectTitle: "FitSure", githubLink: "https://github.com/Shantanu993/FitSure" },
	{ teamName: "Tikdum", projectTitle: "AI Badminton Stroke Validator", githubLink: "https://github.com/karttikjangid/AI_BadmintonCoach" },
	{ teamName: "Sriram Kulkarni", projectTitle: "GYMBRO", githubLink: "https://github.com/BEASTSHRIRAM/GymBro" },
	{ teamName: "Sundaresan C", projectTitle: "DriveSense AI", githubLink: "https://github.com/SundaresanC/Drivesense-AI" },
	{ teamName: "Jasmeen", projectTitle: "DevMentor AI", githubLink: "https://github.com/jass2422/devmentorai" },
	{ teamName: "Swayam Bansal", projectTitle: "RISM", githubLink: "https://github.com/swymbnsl/rism" },
	{ teamName: "CodeCatalysts", projectTitle: "AceView", githubLink: "https://github.com/SKfaizan-786/aceview" },
	{ teamName: "Rehan Rais Pinjari", projectTitle: "SpeakAI", githubLink: "https://github.com/xemorph64/SpeakAI.git" },
	{ teamName: "Divy Deshmukh", projectTitle: "Interview Shield AI", githubLink: "https://github.com/DivyDeshmukh/interview-shield-ai" },
	{ teamName: "Shikhar Verma", projectTitle: "Vision Quest RPG", githubLink: "https://github.com/Shikhyy/Vision-Quest" },
	{ teamName: "Mrityunjay Tiwari", projectTitle: "PrepNova AI Interviewer", githubLink: "https://github.com/mrityunjay-tiwari/stream-interview-be" },
	{ teamName: "Arpit Singh", projectTitle: "ANTON", githubLink: "https://github.com/Renegade2345/Anton" },
	{ teamName: "Manjunath Patil", projectTitle: "SignFlow", githubLink: "https://github.com/manjunath5513/VisionProtocol" },
	{ teamName: "Tambadi Ruchika", projectTitle: "Guardnel", githubLink: "https://github.com/Ruchi0214/guardnel" },
	{ teamName: "Mog Squad", projectTitle: "Courtroom Video Analyzer", githubLink: "https://github.com/Keerthivasan-Venkitajalam/Courtroom-Video-Analyzer-Agent" },
	{ teamName: "Poonam Pawar", projectTitle: "SimbaSense", githubLink: "https://arc.net/l/quote/iakhbtgm" },
	{ teamName: "Mohd Irfan Khan", projectTitle: "Vision ETL Pipeline", githubLink: "https://github.com/ig-mik1/vision-etl-pipeline" },
	{ teamName: "Ramaswamy", projectTitle: "BigTB6", githubLink: "https://github.com/LE-TAPU-KOKO/big-tb6" },
	{ teamName: "Harish Kotra", projectTitle: "PosturePaladin", githubLink: "https://github.com/harishkotra/posture-paladin" },
	{ teamName: "Soumik", projectTitle: "SuperPong", githubLink: "https://github.com/emSoumik/SuperPong" },
	{ teamName: "Srinivas Sivaratri", projectTitle: "PlayCast", githubLink: "https://github.com/sivaratrisrinivas/playcast" },
	{ teamName: "Rishi Jat", projectTitle: "IntentLens", githubLink: "https://github.com/rishi-jat/IntentLens-Realtime-Vision-Agent" },
	{ teamName: "Aryan Gupta", projectTitle: "Titan Ultra", githubLink: "https://github.com/aryangupta4088/titan-ultra-ai-coach..git" },
	{ teamName: "Nancy Sangani", projectTitle: "SafeZone AI", githubLink: "https://github.com/nancysangani/safezone-ai-vision-agent" },
	{ teamName: "M Varshith", projectTitle: "Pluely", githubLink: "https://github.com/varshithm7x/Pluely" },
	{ teamName: "Syed Basheer Ahamed", projectTitle: "InterviewAce", githubLink: "https://github.com/its-bash33r-here/Vision-Hackathon" },
	{ teamName: "Vaibhav Shukla", projectTitle: "ARGUS", githubLink: "https://github.com/Vaibhav13Shukla/argus" },
	{ teamName: "B. Jayaram", projectTitle: "Surgical Scrub AI", githubLink: "https://github.com/Bonthujayaram/Vision-Agents-surgical-scrub/" },
	{ teamName: "Ariya", projectTitle: "CardioSim AI", githubLink: "https://github.com/Ariya-rithvik/VisionAgent" },
	{ teamName: "Divine Victor", projectTitle: "WitnessAI", githubLink: "https://github.com/Loneewolf15/WitnessAi" },
	{ teamName: "Caleb Chandrasekar", projectTitle: "Joey Frontend Expert", githubLink: "https://github.com/calebjubal/vision-agent-hack" },
	{ teamName: "ByteSight (Syahba)", projectTitle: "Luma", githubLink: "https://github.com/Gold-1234/vision_hackathon" },
	{ teamName: "Onkar Pawar", projectTitle: "FreshAI", githubLink: "https://github.com/OnkarPawar1/FreshAI" },
	{ teamName: "Abhinav Gupta", projectTitle: "Sentinel Safety Agent", githubLink: "https://github.com/Abhinavgupta2404/Sentinel-Real-Time-Safety-Security-Monitoring-Agent" },
	{ teamName: "Kesavaraja M", projectTitle: "Semantic Cinematographer", githubLink: "https://github.com/Kesavaraja67/the-semantic-cinematographer" },
	{ teamName: "Rahul Pandey", projectTitle: "RoundZero", githubLink: "https://github.com/CoderRahul01/roundZero" },
];

export { winningProjects, topProjects, otherProjects };
