const winningProjects = [
	{
		teamName: "Anish",
		projectTitle: "TrendOps",
		description:
			"TrendOps is a governance-first, MCP-native AI agent swarm that transforms live YouTube trend data into strategic, investor-ready intelligence. Instead of a monolithic application, TrendOps decomposes the intelligence lifecycle into governed MCP tools — validation, data ingestion, analytics, and executive insight generation — orchestrated through a control-plane architecture. It enforces policy guardrails (region validation, rate limits), performs TF-IDF keyword extraction and K-Means clustering to detect emerging subcultures, and generates structured strategic reports via LLM — all with full execution tracing and cost observability. Built for the 2 Fast 2 MCP Hackathon, TrendOps demonstrates modular orchestration, enterprise-grade governance, and production-ready AI tool exposure.",
		githubLink: "https://github.com/anish-maheshwari/TrendOps-",
		deployedLink: "https://trendops.co.in/",
		youtubeEmbed: "https://www.youtube.com/embed/Ju9RAELt-4Y",
		prize: "1st Place",
	},
	{
		teamName: "Veer Adyani",
		projectTitle: "Preffer",
		description:
			"A full-stack AI-powered portfolio platform where a user can create and publish professional public pages, attach an AI representative to those pages, and track visitor behavior with analytics. Lets users sign in with Google OAuth, provides a 7-step wizard to build a portfolio or company page, generates and edits section content through AI chat, publishes pages to public slug routes, optionally enables a public AI representative for each published page, tracks page views and chat sessions, extracts business intents from visitor conversations, and gives owners analytics dashboards plus AI-generated business insights. Exposes MCP tools so external AI systems can manage portfolios programmatically. Built with Next.js App Router, React 19, Express, PostgreSQL, Gemini, and optional Archestra LLM proxy and A2A agent routing.",
		githubLink: "https://github.com/veeradyani222/my-portfolio",
		deployedLink: "https://preffer.me",
		youtubeEmbed: "https://www.youtube.com/embed/tsDKUfw1SX8",
		prize: "2nd Place",
	},
	{
		teamName: "Althaf Asharaf",
		projectTitle: "AgriBot",
		description:
			"AgriBot is an AI-powered agricultural operations platform that provides farmers with real-time, phase-aware crop guidance through specialized MCP agents all orchestrated through Archestra. Features RBAC to protect farmer privacy, Dual LLM Security to protect from prompt injection attacks, and MCP Registry integration with the National Statistics Office (eSankhyiki) for wholesale price trends and inflation data. Archestra turns seven independent servers into one secure, intelligent platform that farmers can trust.",
		githubLink: "https://github.com/Althaf66/Agri-bot",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/G5MXBTyBqmc",
		prize: "3rd Place",
	},
];

const topProjects = [
	{
		teamName: "Anurag Sharma",
		projectTitle: "Sentinel",
		description:
			"Sentinel is an autonomous, goal-oriented system administration framework designed to turn a standard operating system into a self-healing, intent-driven environment. Unlike traditional automation scripts, Sentinel utilizes Large Language Models (LLMs) to interpret complex user goals and executes multi-step workflows across isolated virtual machines and local host environments. Archestra serves as the Governance and Control Plane, acting as a secure safety layer that bridges the gap between autonomous AI reasoning and sensitive system-level operations.",
		githubLink: "https://github.com/asHawcker/linux-guardian-mcp",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/ng6T5U_pfE0",
	},
	{
		teamName: "Jayashree",
		projectTitle: "SRE Sentinal",
		description:
			"Sentinel is an autonomous Site Reliability Engineering (SRE) agent that continuously watches system health, uses AI to understand what went wrong, applies safety checks, and fixes issues automatically when safe or with human approval when needed. Archestra is used as the orchestration layer that connects to the Sentinal MCP server, with tools like get_infrastructure_status, incident_history, trigger_alert, and approvals available through Archestra's Chat UI.",
		githubLink: "https://github.com/Jayashree1743/SRE-SENTINAL",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/2S3X5FB3Mi8",
	},
	{
		teamName: "Tosif",
		projectTitle: "On-Call Agent",
		description:
			"AI-powered On-Call Agent that automates incident investigation by correlating real GitHub commits, logs, and tickets using Archestra MCP — solving the \"2 AM Nightmare\" for on-call engineers. Uses Archestra as the core integration layer; the MCP Gateway connects the Next.js backend to GitHub via the GitHub Copilot MCP Server. Jira, Slack, and Datadog can be added with zero code changes by simply installing their MCP servers in the Archestra Dashboard.",
		githubLink: "https://github.com/tosif121/mcp-oncall-agent.git",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/20m2neXIM4I",
	},
	{
		teamName: "YASH BANSAL",
		projectTitle: "AAGIL",
		description:
			"AAGIL (Adaptive Agent Genetic Integrity Layer) is a production-grade behavioral assurance platform that sits in front of large language models and agent systems to enforce safety, reliability, and response quality through a multi-layer, evolutionary decision pipeline. It combines behavioral firewalling, multi-model parallel generation, adversarial drift detection, evolutionary variant optimization, tool runtime protection, and persistent performance memory. Archestra is used as the orchestration backbone for coordinating multiple specialized AI agents (Gene Agent, Evaluator Agent, Behavioral Firewall Agent, Red-Team Agent, Tool Guard Agent) through structured MCP-based communication.",
		githubLink: "https://github.com/demonstrikkk/AAGIL_FAST2FAST",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/oTMJF1BpgC4",
	},
	{
		teamName: "Akash M",
		projectTitle: "PitCrew Incidents",
		description:
			"PitCrew Incidents is a tool-driven multi-agent incident response workflow built inside Archestra.AI. It runs a strict incident pipeline, pulls real evidence from Grafana Cloud Prometheus, automatically creates a GitHub issue in the project repo, posts a Slack update with the issue URL, and generates an incident summary artifact — all via real MCP tool calls with no mocked outputs. Archestra.AI was used as the runtime to build and run the full multi-agent incident workflow with a Master Agent coordinating four agents in strict order.",
		githubLink: "https://github.com/Akash-How/pitcrew-incidents",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/OLO5L_fgJeY",
	},
	{
		teamName: "Allen Saji",
		projectTitle: "Corvus",
		description:
			"A Solana DeFi Intelligence MCP server. Using Archestra to orchestrate the entire server lifecycle, manage secrets, and bridge AI agents to on-chain tools (wallet analysis, token prices, DeFi positions). Archestra makes the MCP server instantly discoverable and deployable — no manual wiring needed.",
		githubLink: "https://github.com/Allen-Saji/corvus",
		deployedLink: "https://corvus.allensaji.dev/",
		youtubeEmbed: "",
	},
	{
		teamName: "Aryan Kumar",
		projectTitle: "MCP Guardian",
		description:
			"MCP Guardian is an MCP server that audits other MCP servers. It reads tool definitions from Archestra's API, runs them through 50+ vulnerability patterns and an LLM deep scan, then writes real security policies back to Archestra that block dangerous tools. Scan, detect, lock down — one chat command. Includes a malicious demo server with 7 intentionally broken tools to prove it catches everything. Runs inside Archestra's embedded K8s as a managed pod, deployed through Terraform with the Archestra provider.",
		githubLink: "https://github.com/aryan877/mcp-guardian",
		deployedLink: "https://guardian.aryankumar.dev/",
		youtubeEmbed: "",
	},
	{
		teamName: "Tharunya Pathipati",
		projectTitle: "PitStop Check",
		description:
			"PitStop Check is an MCP \"trust and safety inspector\" that audits any MCP server before you connect it to your agent. It can inspect MCP targets over stdio or HTTP, run lint + conformance checks on tool metadata, benchmark listTools latency, compute a risk level, export an approval bundle, generate a markdown trust report, and compare runs to show what changed between two versions. Archestra was used as the development and verification environment for MCP tool behavior.",
		githubLink: "https://github.com/Tharunya07/pitstop-check",
		deployedLink: "",
		youtubeEmbed: "https://www.loom.com/embed/4b279920354748de94c1881f8af80957",
	},
	{
		teamName: "Sahil Ali",
		projectTitle: "FluxAI",
		description:
			"FluxAI is a multi-tenant cost and quota management system for MCP agents. It acts as a \"policy firewall\" that intercepts tool and model calls, evaluates them against configured budgets and policies, and makes intelligent routing decisions (allow/deny/downgrade). Integrated with Archestra as the MCP host that runs the FluxAI MCP server; agents call flux-ai.check_and_route before invoking expensive LLM tools so Archestra delegates routing and budget checks to FluxAI.",
		githubLink: "https://github.com/a-sahil/FluxAI",
		deployedLink: "",
		youtubeEmbed: "",
	},
	{
		teamName: "BARATH",
		projectTitle: "Chip Design Agent",
		description:
			"An MCP server that gives AI agents the ability to design, synthesize, and fabricate digital chips using open-source EDA tools — entirely through natural language. A user describes a digital circuit in plain English, and the agent autonomously writes synthesizable Verilog RTL, synthesizes with Yosys (Sky130 PDK), runs the full RTL-to-GDSII flow via OpenLane, analyzes PPA metrics, and renders a visual preview of the final GDSII layout. Deployed as a self-hosted MCP server within Archestra's Kubernetes cluster; Archestra's runtime acts as the secure bridge between the LLM and Dockerized EDA tools.",
		githubLink: "https://github.com/BARATHM111/Chip-Design-Agent---MCP-EDA-Server-for-Archestra",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/oLSgR-ygOV0",
	},
	{
		teamName: "Sayan Ganguly",
		projectTitle: "Refund Pro",
		description:
			"Refund Pro is an autonomous legal orchestration agent designed to enforce consumer rights in India. It automates the refund lifecycle by calculating statutory interest penalties and drafting legally binding notices based on real case precedents. Features an aggression optimizer that adjusts legal tone based on company behavior and a precedent engine that cites specific case numbers. Archestra is used as the central control plane to orchestrate the Dockerized MCP server, with Dual LLM security to prevent prompt injections when processing untrusted user data.",
		githubLink: "https://github.com/bitWise72/refund-pro-mcp",
		deployedLink: "https://crooked-white-fly.fastmcp.app/mcp",
		youtubeEmbed: "https://www.youtube.com/embed/elUVkkI3M2w",
	},
	{
		teamName: "Sarthak Negi",
		projectTitle: "Secure Multi-Agent SRE Dashboard",
		description:
			"When an alert fires, this system uses coordinated AI agents to investigate, diagnose, and safely remediate incidents in seconds. One agent analyzes metrics, another correlates logs, and a remediation agent validates and proposes fixes — with guardrails like dry runs and strict blocklists. Archestra is the central orchestration layer, hosting both the Alert Triage Agent and the Remediation Agent with structured conversations, controlled tool access through MCP servers, and secure agent-to-agent handoffs.",
		githubLink: "https://github.com/sarthaksarthak9/AgentPitCrew",
		deployedLink: "",
		youtubeEmbed: "https://www.loom.com/embed/9ce97b9191b4491dbd0251cf39f18f78",
	},
	{
		teamName: "Ariya P",
		projectTitle: "ContextOS",
		description:
			"ContextOS addresses Notification Fatigue with Archestra as the Production Brain and LLM Orchestration Layer. Archestra acts as the decision-making engine that receives natural language and determines the appropriate course of action, connects to the Python MCP server via SSE, and discovers tools like schedule_event, trigger_alert, create_ticket, and Tasks/Reminders. When a user sends a command like \"Schedule a meeting with Alice,\" Archestra's LLM analyzes the text and executes the appropriate tool call.",
		githubLink: "https://github.com/Ariya-rithvik/context-os-archestra-hackathon",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/Fwwz6GXNgjQ",
	},
	{
		teamName: "Aaryan Guglani",
		projectTitle: "Vyapaar MCP",
		description:
			"Vyapaar MCP is a high-performance financial governance layer and MCP server that acts as an autonomous firewall between AI agents and the Razorpay X banking platform. It intercepts every payout attempt, validates against a strict policy engine, checks vendor reputation, and ensures Human-in-the-Loop for high-risk decisions. Archestra acts as the Security Gateway and Enterprise Orchestrator with Deterministic Security (Foundry Model), Dual-LLM Quarantine, and operational layer for secrets and sidecars.",
		githubLink: "https://github.com/guglxni/vyapaar-mcp",
		deployedLink: "",
		youtubeEmbed: "",
	},
	{
		teamName: "Kishan Patel",
		projectTitle: "SecureOps Sentinel",
		description:
			"SecureOps Sentinel is a multi-agent system that triages production incidents using AI while defending against prompt injection attacks hiding in log data. When a DevOps engineer asks \"What's wrong with our web-api?\", three AI agents collaborate: LogAnalyzerAgent, IncidentCommanderAgent, and RemediationAgent. Archestra's Dual LLM quarantine and Dynamic Tools neutralize prompt injection attacks while A2A delegation ensures the incident still gets handled.",
		githubLink: "https://github.com/thekishandev/secureops-sentinel",
		deployedLink: "",
		youtubeEmbed: "",
	},
	{
		teamName: "Yemuka Shyam",
		projectTitle: "ShellGuard",
		description:
			"ShellGuard is an intelligent terminal safety assistant that mitigates command-line risks by intercepting and analyzing execution requests in real-time. Leveraging Archestra MCP as its core decision engine, it assesses the intent and potential consequences of each command. When high-risk operation is detected, ShellGuard halts execution and provides detailed risk analysis and safer, context-aware alternatives. Archestra serves as the primary intelligence engine with comprehensive observability and fallback to Gemini API when unreachable.",
		githubLink: "https://github.com/Shyamyemuka/ShellGuard",
		deployedLink: "https://shell-guard.vercel.app/",
		youtubeEmbed: "https://www.youtube.com/embed/FyiwOA1g-Gs",
	},
	{
		teamName: "Gurshaan Singh Dult",
		projectTitle: "Runbook Executor",
		description:
			"Autonomous Infrastructure Incident Response: an AI agent system that detects infrastructure anomalies, interprets human-written runbooks, and executes validated remediation steps automatically. Monitor MCP observes metrics and provides anomaly detection; Executor MCP performs remediation (restart, scale, rollback) with rate limits and action validation. Orchestrator Agent runs on Archestra using Gemini to interpret runbooks and coordinate both MCPs. Strict read/write separation creates clear governance boundaries.",
		githubLink: "https://github.com/gurshaan17/runbook",
		deployedLink: "https://runbook.gurshaan.xyz/",
		youtubeEmbed: "https://www.youtube.com/embed/L9aImJvm5FY",
	},
	{
		teamName: "Pratham Chauhan",
		projectTitle: "SecureOps AI",
		description:
			"SecureOps AI is an autonomous incident response platform that connects to live incident feeds through custom MCP servers, uses Groq's Llama 3.3 70B for intelligent triage, and automatically creates prioritized GitHub tickets in under 30 seconds. To prove security, a real prompt injection attack was embedded in a test incident and the system correctly ignored the malicious instructions. Archestra is the secure orchestration backbone with two custom MCP servers (Incident Feed + GitHub Ticketing) and dual-LLM security quarantine.",
		githubLink: "https://github.com/Pratham271/secure-ops",
		deployedLink: "",
		youtubeEmbed: "https://www.youtube.com/embed/xRgujguZfOU",
	},
];

const otherProjects: { teamName: string; projectTitle: string; githubLink: string }[] = [
	{ teamName: "Akash Adsare", projectTitle: "AEGIS - Multi-agent medical diagnostic swarm on Archestra", githubLink: "https://github.com/akashadsare/AEGIS" },
	{ teamName: "Akash Singh", projectTitle: "TikTok - Short-video sharing web application", githubLink: "https://github.com/AkashS817/Tic-Tac-Toe" },
	{ teamName: "Saif Ali Shaik", projectTitle: "SCIM Gateway for Archestra", githubLink: "https://github.com/saif-shines/scim-gateway-archestra" },
	{ teamName: "Dev Parikh", projectTitle: "EscalationPilot MCP - Multi-agent ticket triage for e-commerce", githubLink: "https://github.com/Dev0907/EscalationPilot-MCP.git" },
	{ teamName: "Ravi Sahu", projectTitle: "PitStop SRE Copilot - AI incident response orchestrator", githubLink: "https://github.com/RaviSahu1520/pitStop.git" },
	{ teamName: "Shivansh Bagga", projectTitle: "TrustLayer AI - Backend trust layer for safe AI adoption", githubLink: "https://github.com/baggashivansh/TrustLayer-AI" },
	{ teamName: "Ganeswar Sahoo", projectTitle: "Docs Helper Agent - MCP-powered documentation Q&A", githubLink: "https://github.com/ganeswar-sahoo/docs-helper-agent-archestra" },
	{ teamName: "Manas Dutta", projectTitle: "Cerberus - Multi-agent release gatekeeper (SHIP/NO_SHIP)", githubLink: "https://github.com/manasdutta04/Cerberus" },
	{ teamName: "Shiva", projectTitle: "Autonomous Security Agent Swarm - AI security assessment system", githubLink: "https://github.com/shivakumar2006/mcp" },
	{ teamName: "Sachin Singh", projectTitle: "MCP Refactoring Orchestrator - AI-powered code refactoring", githubLink: "https://github.com/Sachinsingh2002/mcp-refactoring-orchestrator" },
	{ teamName: "Malay Khant", projectTitle: "Vector similarity - MCP intelligent agent with RAG", githubLink: "https://github.com/opusxdev/vector-similarity" },
	{ teamName: "Jaya Dubey", projectTitle: "TestPilot - Analyzes code changes for testers", githubLink: "https://github.com/jaya6400/testpilot-archestra" },
	{ teamName: "Think Twice", projectTitle: "SuperMCP-CLI - Build your own MCPs", githubLink: "https://github.com/SpandanM110/SuperMCP-CLI" },
	{ teamName: "Nilanjan Saha", projectTitle: "ChainPilotAI - Real-time supply chain intelligence", githubLink: "https://github.com/Devnil434/ChainPilotAI.git" },
	{ teamName: "Shashank", projectTitle: "Python MCP server - Async, Pydantic, stdio transport", githubLink: "https://github.com/Shashank-Mengani/MCP" },
	{ teamName: "Dhruv Gangal", projectTitle: "Lucid - AI requirements analysis & decision engine", githubLink: "https://github.com/DHRUVGANGAL/lucid-backend/tree/main" },
	{ teamName: "Jiten Kumar Mohanty", projectTitle: "MCP Sentinel - SOC for AI agent platforms", githubLink: "https://github.com/Jitenmohanty/mcp-sentinel" },
	{ teamName: "RSPR", projectTitle: "AI-powered security investigation with MCP & PostgreSQL", githubLink: "https://github.com/RayhanSK/Archestra-Hackathon-.git" },
	{ teamName: "Lokesh", projectTitle: "DevOps Copilot - Autonomous incident detection & resolution", githubLink: "https://github.com/lokeshsw2/Devops-Copilot" },
	{ teamName: "Devata Devs", projectTitle: "AI File Assistant", githubLink: "https://github.com/VivekBardava-OG/ai-file-assistant" },
	{ teamName: "Achyut Natekar", projectTitle: "Sentinel - High-performance secure MCP agent (Fortress architecture)", githubLink: "https://github.com/AceAchyut/sentinel-mcp" },
	{ teamName: "Aashutosh Kumar Bhardwaj", projectTitle: "Repofy - AI-driven repo documentation & insights", githubLink: "https://github.com/aashutoshkumarbhardwaj/Repofy_web" },
	{ teamName: "Markhors", projectTitle: "QueryMaster - Natural language PostgreSQL queries via MCP", githubLink: "https://github.com/junaiddshaukat/querymaster" },
	{ teamName: "Solo_Nrusingh", projectTitle: "Archestra MCP project - Workflow orchestration demo", githubLink: "https://github.com/nrusingh-07/archestra-mcp-project" },
	{ teamName: "Kanav Jeet Singh", projectTitle: "SYNAPSE-X - Self-organizing hierarchical AI engineering system", githubLink: "https://github.com/KanavjeetS/AI-Systems-Architect" },
	{ teamName: "Think Twice", projectTitle: "InfraWhisperer - Natural language infrastructure management", githubLink: "https://github.com/Tusharkshahi/InfraWhisperer" },
	{ teamName: "Manju Vasanth", projectTitle: "OpsPilot MCP Lite - AI DevOps assistant", githubLink: "https://github.com/ManjuVasanth/OpsPilot-MCP.git" },
	{ teamName: "Kartik Garg", projectTitle: "archestra-mcp-init - CLI to scaffold secure MCP servers", githubLink: "https://github.com/Kartikgarg74/archestra-mcp-init" },
	{ teamName: "Rohan Sunwar", projectTitle: "Archestrate - AI-powered AWS IAM security audit agent", githubLink: "https://github.com/Rohansunwar5/archestrate-hackathon.git" },
	{ teamName: "Dhruva Wani", projectTitle: "MedGuard - HIPAA-compliant clinical intelligence", githubLink: "https://github.com/dhruvawani17/medguard" },
	{ teamName: "Aymaan Pathan", projectTitle: "AgentOS - DevOps AI operations (Runbook, Agent, Monitor modes)", githubLink: "https://github.com/AymaanPathan/Agent-OS" },
	{ teamName: "Trupti Ganeshkar", projectTitle: "AI UI Critique Assistant", githubLink: "https://github.com/Tru06/ai-ui-critique" },
	{ teamName: "Code_Unions", projectTitle: "NEXUS - Intelligent MCP broker for multi-server workflows", githubLink: "https://github.com/sahil1798/nexus.git" },
	{ teamName: "Ayush Gautam", projectTitle: "OnboardAI - AI employee onboarding agent", githubLink: "https://github.com/arunsingh-creator/2Fast2MCP" },
	{ teamName: "Harsh Kumar", projectTitle: "MCP Agent Control Tower - Enterprise AI orchestration", githubLink: "https://github.com/HrsFlex/2fast2mcp" },
	{ teamName: "Will Wild", projectTitle: "PitCrew - Secure MCP workflow racing suite on Archestra", githubLink: "https://github.com/wildhash/pitcrew" },
	{ teamName: "Samiksha Lambe", projectTitle: "Guardian Angel - Zero-Trust medical inventory MCP agent", githubLink: "https://github.com/samikshalambe/guardian-angel-mcp" },
	{ teamName: "Mohit Vijay Jeswani", projectTitle: "Archestra Sentinel - Security & governance for AI agents", githubLink: "https://github.com/mohitjeswani01/archestra-sentinel" },
	{ teamName: "Shrikant Kole", projectTitle: "MailGuard - AI email threat triage platform", githubLink: "https://github.com/shrikantkole1/mailguard.git" },
	{ teamName: "APIx Predators", projectTitle: "HyperShift - Autonomous cloud orchestration platform", githubLink: "https://github.com/GautamTalksDev/HyperShift" },
	{ teamName: "PeakPanthers", projectTitle: "AutoOps AI - Self-healing infrastructure with Chaos Monkey", githubLink: "https://github.com/Captain1508/autoops-ai" },
	{ teamName: "Verosity", projectTitle: "CostGuard AI - Autonomous cloud & LLM cost optimization", githubLink: "https://github.com/AaKaShhhhhhhhh/Costguard" },
	{ teamName: "Roshan Rateria", projectTitle: "AgentPit - Formula 1 pit wall for AI agents", githubLink: "https://github.com/roshanrateria/agentpit" },
	{ teamName: "Haseeb Ur Rehman", projectTitle: "VR/AI Mental Health Companion for Seniors", githubLink: "https://github.com/marine9056/virtual-ai-assistant-for-elder" },
	{ teamName: "ContextWeaver", projectTitle: "ContextWeaver - REST API to MCP server in under a minute", githubLink: "https://github.com/SKfaizan-786/contextweaver" },
	{ teamName: "Hemanth C S", projectTitle: "AutoPilot - MCP-native incident detection & remediation", githubLink: "https://github.com/hemanthcs34/mcp-project" },
	{ teamName: "phoneix", projectTitle: "Phantom Credential Checker - Security auditing with Archestra", githubLink: "https://github.com/anitha646/phantom-credential-checker" },
	{ teamName: "Dev Johri", projectTitle: "SentinelMCP - MCP-native AI agent auditor", githubLink: "https://github.com/incruder1/sentinel_mcp" },
	{ teamName: "Arjun Mukesh", projectTitle: "Switcheroo - Agentic environment control (lighting, switches)", githubLink: "https://www.github.com/arjunmukeshh/switcheroo" },
	{ teamName: "Biplab Bera", projectTitle: "AegisFlow - AI real-time monitoring for manufacturing", githubLink: "https://github.com/bishalbera/aegisflow" },
	{ teamName: "Saai Aravindh Raja", projectTitle: "ShieldOps - AI Security Operations Center", githubLink: "https://github.com/SaaiAravindhRaja/shieldops" },
	{ teamName: "NeuralOps", projectTitle: "IncidentIQ - Autonomous incident root cause via Archestra", githubLink: "https://github.com/Developer-atomic-amardeep/NeuralOps-Incident-IQ.git" },
	{ teamName: "Tushar Khatri", projectTitle: "Juryline - Hackathon judging dashboard", githubLink: "https://github.com/tusharkhatriofficial/juryline" },
	{ teamName: "PromptPirates", projectTitle: "AI SRE Assistant - Log monitoring & Slack alerts", githubLink: "https://github.com/JejurkarYash/ai-sre-agent" },
	{ teamName: "Aditya Suryawanshi", projectTitle: "GroundedAgent - SDK-aware multi-agent code generation", githubLink: "https://github.com/Adidem23/SDK_Grounding_Agent" },
	{ teamName: "MCP devs", projectTitle: "Offline AI Terminal Agent - 42 tools, Ollama, no cloud", githubLink: "https://github.com/Omkar-S-Kulkarni/2fast2mcplocalmcpserverclient" },
	{ teamName: "Coding Bugs", projectTitle: "AI detector - Human vs AI content analysis", githubLink: "https://github.com/kainturasourav0-star/Ai-detector" },
	{ teamName: "Kshitij Gaikwad", projectTitle: "GitAgent Master - PR review & Linear tickets via Archestra", githubLink: "https://github.com/automationwithk-ai/taskflow" },
	{ teamName: "Dopamine + Throttle", projectTitle: "Sentinel Zero-Trust Security Vault - PII masking for AI", githubLink: "https://github.com/Super-Crazy/sentinel-vault" },
	{ teamName: "M Varshith", projectTitle: "Procrastination Score agent - Productivity tracking", githubLink: "https://github.com/varshithm7x/2-Fast-2-MCP-Hackathon" },
	{ teamName: "Yadnyesh Kolte", projectTitle: "Multi-agent README generator", githubLink: "https://github.com/yadnyeshkolte/readmere" },
	{ teamName: "Jasmeen", projectTitle: "AI Incident Commander - Incident analysis & remediation", githubLink: "https://github.com/jass2422/ai-incident-commander" },
	{ teamName: "EVS", projectTitle: "AI-powered MCP workflow automation with Archestra", githubLink: "https://github.com/vishnu-varthan1" },
	{ teamName: "Srinidhi P", projectTitle: "Sentinel - Autonomous infrastructure orchestration (power, hydro, sewage)", githubLink: "https://github.com/Srinidhi0604/ArchestraProject" },
	{ teamName: "Dipak", projectTitle: "AI Technical Interviewer - Multi-agent orchestration", githubLink: "https://github.com/vision39/arhak" },
	{ teamName: "Siddhant Prateek Mahanayak", projectTitle: "Reefline - Container image hygiene & runtime security", githubLink: "https://github.com/siddhantprateek/reefline" },
	{ teamName: "soham kharat", projectTitle: "Secure Blender script swarm - Coordinator-Executor architecture", githubLink: "https://github.com/Sohamkhrt/arcestral_blender_security" },
	{ teamName: "Bhuvan C V", projectTitle: "PitCrew Mechanic MCP - Autonomous SRE via Archestra", githubLink: "https://github.com/Bhuvan-08/pitcrew-ai" },
	{ teamName: "Vishal Sharma", projectTitle: "AWS infrastructure with Natural Language", githubLink: "https://github.com/Vishal2002/aws-agent" },
	{ teamName: "Balasubramanian Shanmugham", projectTitle: "AI-powered logistics tracking with Archestra", githubLink: "https://github.com/balasus1/chain-guard-tambo/blob/main/WEEK2_ARCHESRTA_PLAN.md" },
	{ teamName: "Team Xspark", projectTitle: "CodeHealth MCP - AI code quality orchestrator", githubLink: "https://github.com/Killer2OP/CodeHealth-MCP" },
	{ teamName: "Mohammad Azam", projectTitle: "Sentinel - Human-in-the-loop biometric firewall for AI", githubLink: "https://github.com/Azam0221/Python_Script_Archestra" },
	{ teamName: "Anurag Thakur", projectTitle: "GitHub Issue Triage MCP Server", githubLink: "https://github.com/DevAnuragT/autotriage_mcp" },
	{ teamName: "TrustLayer", projectTitle: "Bastion - Deterministic AI governance for data systems", githubLink: "https://github.com/HansujaB/bastion-mcp" },
	{ teamName: "Vaibhavi.T", projectTitle: "NeighborShare - AI hyper-local sharing platform", githubLink: "https://github.com/tvaibh27/Complete-NeighborShare-project-for-2-FAST-2-MCP-hackathon-" },
	{ teamName: "KLohithSaradhi", projectTitle: "Ridwan - AI incident response + ChatOps platform", githubLink: "https://github.com/Vishwa-docs/Ridwan-2Fast2MCP-WeMakeDevs-Archestra-Hackathon-2026" },
	{ teamName: "Aditya Kumar Puri", projectTitle: "LameMemory - MCP server for LLM persistent memory", githubLink: "https://github.com/puri-adityakumar/lamememory" },
	{ teamName: "The Feb Four", projectTitle: "AI supply chain decision assistant", githubLink: "https://github.com/Om-Goplani/KargoPilot" },
	{ teamName: "Ankit Sharma", projectTitle: "AI sales prospecting agent - Maps, Tavily, HubSpot", githubLink: "https://github.com/akcode7/sales-automation-agent" },
	{ teamName: "Cognexa", projectTitle: "Prompt Governance Hub for Archestra", githubLink: "https://github.com/vedanshun05/prompt-governance-hub" },
	{ teamName: "Aidhunik India", projectTitle: "ETL with Archestra - Elasticsearch to PostgreSQL", githubLink: "https://github.com/devKanishk15/archestra-ai-project" },
	{ teamName: "Mano Janani R", projectTitle: "MCP agent for edtech - Tutorial links with Ollama", githubLink: "https://github.com/ManoJananiR/Hackathon-2-MCP-" },
	{ teamName: "Arjun Sharma", projectTitle: "OnboardingOS - 4-week onboarding into 3 days", githubLink: "https://github.com/Spidy29/archestra-ai-mcp-hackathon" },
	{ teamName: "Balaji Thukuntala", projectTitle: "QuerySense - Multi-agent SQL optimization on Archestra", githubLink: "https://github.com/BalajiReddy1/querysense" },
	{ teamName: "Shubham Kumar", projectTitle: "PMG - Personal Memory Gateway with PII firewall", githubLink: "https://github.com/shubham-01-star/mcp-personal-memory-gateway" },
	{ teamName: "ANIRUDDHA ADAK", projectTitle: "Privacy-first DevSecOps pipeline - 4 local MCP agents", githubLink: "https://github.com/aniruddhaadak80/SecureOps-AI" },
	{ teamName: "DreamCatchers", projectTitle: "AI Hallucination Guard - Multi-agent fact verification", githubLink: "https://github.com/yasminshaik125/ai-hallucination-guard" },
	{ teamName: "suyog gadekar", projectTitle: "Sentinel AI - Autonomous incident response with guardrails", githubLink: "https://github.com/Suyog9402/incident-response-demo.git" },
	{ teamName: "Pravin Wavare", projectTitle: "MCP Incident Slayer - Autonomous SRE agent", githubLink: "https://github.com/yash9154/MCP-Incident-Slayer" },
	{ teamName: "Cian", projectTitle: "SecureProcure - AI procurement with trust-aware security", githubLink: "https://github.com/mutaician/SecureProcure" },
	{ teamName: "FlowForge", projectTitle: "FlowForge - No-code backend builder from natural language", githubLink: "https://github.com/piyushagarwal-55/Flowforge" },
	{ teamName: "Shantanu Gahtori", projectTitle: "CodeAudit - Multi-agent code audit with Archestra", githubLink: "https://github.com/Shantanu993/Archestra2FastMCP" },
	{ teamName: "Devam Patel", projectTitle: "Angler - Active defense AI for enterprise chatbots", githubLink: "https://github.com/devampatel03/Angler" },
	{ teamName: "Sushant Jain (Inquz)", projectTitle: "Google Maps MCP Server for Archestra", githubLink: "https://github.com/Sushant6095/maps-mcp-archestra" },
	{ teamName: "HACK TO THE FUTURE", projectTitle: "DevGuard AI - MCP deployment safety controller", githubLink: "https://github.com/ABHISHEK-PRASAD-BAHELIYA/devguard-ai" },
	{ teamName: "Team Velocity", projectTitle: "Sentinel-ai - Policy-governed n8n workflow orchestration", githubLink: "https://github.com/sparsh0006/sentinel-ai" },
	{ teamName: "Vibe Coders", projectTitle: "Archestra.AI - Multi-agent personal assistant (Finance, MCP)", githubLink: "https://github.com/Himanshu-Goyal9215/archestra_ai" },
	{ teamName: "ai_stole_our_jobs", projectTitle: "SecOps Sentinel - Autonomous Blue Team security analyst", githubLink: "https://github.com/kartiklolla/Arc_SecOps_Sentinel" },
	{ teamName: "pokemon", projectTitle: "Aegis - Zero Trust Security Gateway for MCP agents", githubLink: "https://github.com/Harsh3363/Aegis" },
	{ teamName: "Axen", projectTitle: "AutoClass AI - Google Classroom assignment solver", githubLink: "https://github.com/13507-IN/AutoClass-AI" },
	{ teamName: "Rishi Jat", projectTitle: "ARCHON - Autonomous repo security & hardening", githubLink: "https://github.com/rishi-jat/archon" },
	{ teamName: "Arceus", projectTitle: "Resurrector - Self-healing & disaster recovery on Archestra", githubLink: "https://github.com/bharathkumaarr/resurrector" },
	{ teamName: "404", projectTitle: "Remora - MCP memory server (shared subconscious for agents)", githubLink: "https://github.com/remora-infra/Remora" },
	{ teamName: "Jay Bamroliya", projectTitle: "Policy Copilot MCP - Real-time governance for AI agents", githubLink: "https://github.com/jaybamroliya/policy-copilot-mcp" },
	{ teamName: "Rahul Joshi", projectTitle: "AutoFinance - 13 MCP servers for financial analysis", githubLink: "https://github.com/crypticsaiyan/AutoFinance" },
	{ teamName: "gaurav rawat", projectTitle: "Shadow AI Detector - Centralized AI governance engine", githubLink: "https://github.com/gaurav21-05/shadow-AI-Detector" },
	{ teamName: "Sumit Kumar", projectTitle: "AgentFabric - Multi-agent AI with Dual-LLM sanitization", githubLink: "https://github.com/TheKumaara/AgentFabric" },
	{ teamName: "Shikhar Verma", projectTitle: "AI Parliament - Decentralized agent governance", githubLink: "https://github.com/Shikhyy/AI_Parliament" },
	{ teamName: "Mog Squad", projectTitle: "Recall - Self-learning MCP data agent (SQL insights)", githubLink: "https://github.com/Keerthivasan-Venkitajalam/Recall" },
	{ teamName: "Kesavaraja", projectTitle: "Compliance Sentinel MCP - Zero-Trust cybersecurity auditing", githubLink: "https://github.com/Kesavaraja67/compliance-sentinel-mcp.git" },
	{ teamName: "Abhishek Anand", projectTitle: "Dialectic - Dependency risk assessor (multi-LLM debate)", githubLink: "https://github.com/Rutetid/Dialectic" },
	{ teamName: "Dimension 0", projectTitle: "DataAware-Ops - Prometheus to Linear with Claude AI", githubLink: "https://github.com/RJSIN147/DataAware-Ops" },
	{ teamName: "Domendra", projectTitle: "Guardian - Safety escort assistant (routes, weather, vision)", githubLink: "https://github.com/azadDsync/guardian-mcp-v2" },
	{ teamName: "Manjunath Patil", projectTitle: "Enterprise Compliance Guardian & AI Incident Commander", githubLink: "https://github.com/manjunath5513/Enterprise-compliance" },
	{ teamName: "Aditya", projectTitle: "Antigravity - Chat-first carbon calculations with Climatiq", githubLink: "https://github.com/adi0900/antigravity-econ-frontend" },
	{ teamName: "Sonu", projectTitle: "BastionAI - Security wrapper for resume analysis", githubLink: "https://github.com/sonu-suresh/BastionAI" },
	{ teamName: "Pritam Mukherjee", projectTitle: "MCP AWS - Self-hosted MCP for AWS SRE tools", githubLink: "https://github.com/Pritam-2002/mcp_aws.git" },
	{ teamName: "Aadarsh Shekhar", projectTitle: "AI-SRE - Kubernetes control plane with Archestra", githubLink: "https://github.com/aadarshx22/AI-SRE" },
	{ teamName: "Prasenjeet Kumar", projectTitle: "News Summarizer AI - Multi-agent news intelligence", githubLink: "https://github.com/Prasen2/News_SummarizerAI" },
	{ teamName: "Tasfia Chowdhury", projectTitle: "OpsFlash - Governance-first Git automation MCP", githubLink: "https://github.com/Tasfia-17/OpsFlash.git" },
	{ teamName: "Priyansh Jain", projectTitle: "DarkPulse - Hyper-local dark store orchestrator", githubLink: "https://github.com/Priyansh-Jain/Venture-architect" },
	{ teamName: "Vivek Kumar P", projectTitle: "AI Report Generator - GitHub repo to PDF", githubLink: "https://github.com/vivek-kumar-P/AI_report_generator" },
	{ teamName: "Cantin Squad", projectTitle: "RoleRadar - Job search & resume optimization workflow", githubLink: "https://github.com/TheNova22/2f2mcp_job_automation" },
	{ teamName: "Shuman", projectTitle: "Sentry - MCP TrustOps Command Center", githubLink: "https://github.com/gilfoyleab/Sentry" },
];

export { winningProjects, topProjects, otherProjects };
